[DefaultOutputDestinationSettings = [DestinationDefinition = [Kind = "Reference", QueryName = "DefaultDestination", IsNewTarget = true], UpdateMethod = [Kind = "Replace"], DestinationTypeSettings = [Kind = "Table"]], StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[BindToDefaultDestination = true]
shared #"DIM Storage Location" = let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("nVhbU6NIFP4rXXnYna0Siu6GbvoRMSZZc1Myuu44D5igUiJMEZzZ+fd7+kICkWhilTUkpL+vzzn9nUvPt289l/EzNPyKfsRllSdl76QHL4bwoMTG2GXwyfKxjRkl8LH19/1EwaNdeHQU/FbC5w34rYE7viMM3BG4Ex4sl0leyeVMBPBwPdtzsEJxanuMu52ol6RMl3EOuy6f0/xR4X21q2cTwrHa1bF9l+Iu/GkZv2Sp3I7x04NtDYcRms+uFshC2CEaPdFozpmnbBa2oHi7J3b24InB94/EL8ZNdKDRAvue8dghnaafDcca4WoEYdQ4S6iEYvmPXiREG6dM1mBSq4LXolCaIFtwy14Jvg2uzjSYmp0F2+4srWns7DfA55MUjYvHdF2ly7XWR3iwPgZZcZ8g7FMHo9OyUHA+kA9q+wpiYezbRHviShOu4nz5VOz6/3fwz5sjG0kex6ZUvZCeMM/jXWZcTAMAnibZS2E07kdao9Tz6xg6wu/UqAaHT2lu7JfuU9d2tCHgALeZ74vagXply35N0l+l6yLXLFJwrmN7WBvAXdvF5B0DhsXruqrBUgdE2Jw5KoYCHGGbU+sAj9N8WWT5Bn+lN8eOp+XngQcO3YsPn5Ky/P0zzbJE46dH4aPg2kZno6t+aPSLa/16Xq1Bl+/1PYp/2mg0QV/IXxp+0Tu0Umx2n4fjrXBuP4lXxwv4fz+HJ6qGA/7SuO8K3Hu/qLfwzHE0/vCqbsIX53ksKTx9epfH2h9Mp8EQhX+Eev+zz+FvhpHGj4/BW7Ct1V8WLy8aPN9oZxs7+VHGRpcv4uwwDJKifEzjuoBCBKKa5MO22oF3j8bPg6YHg6PAcGzWpst9PThykzSDbIfUH738KErT2KVwXCprjkpbaHI+7y7cs/4YzX4m5TqJTdGXolFFnyiroegz7hksrN4PBxuIplhoCtc1JQ96AGaq8DsHkNxoEvlwBYSMKTswodD9KNtvyARqfpnEGZpv4jDv7Wlg3oaj1UBhpnp+guqHrGY0J/ui2ekNpAGaXTdHlqnRQd29MNsv4y26LmLnvT1FZMvQxOsi8KSCgEKdBePenjK8pWiFIfpRJskiTjO0iEHOsWZR0yK3iUeEPhACJ+zSnmmHClQBqLfTErds18mjUZkeAhm4IjQZ9uB0VWd7n2wxPIPgTJL/0qXp0vJ0CLc96iidCGG7ukU5vV2xf42sYHrWv4pm09HUAqyWmnpAlxM6OjDQ+vvg4SxahDN01Z8H4cVoOpAkc00y1yTMV50a2jzme60YzyIUTAf9cT+yw0CSXGgS9egamTpp6oprDxTHUHPUV4lOwbQ5rpMqKeP8zzUK47JMIQW15kJDoc2QDKI2QstlM+V3s6DbuFxpqllNtRlhRVt5tDVxF/G6ghQOqizOYRBFs2USy1lmARus0wpxpAqJ8sdi8px441cLyW+ig3Ca/HooXvMV0K5OwM48XsUNIHYRU4OdctijtlDbtLlhkaWXNefmEK5T5XsmE2xsdm0lMCreMKt5kDdIJ+nK2k8ot1e90FJFYodL/sqa+QfmwS/FAxqk92BpFZcNANWzgnLb7gio+t1r0E2hsDyh4EHeB09QnsQlCrJHuB7G1uI1T9dpM66u6gi+Lf2DWi46fFdL3I6ATpJVCsKCheA+ipIYfSkeHmDEvf8d/9XcQ2yDCzUJGuXbo9NrGpucv1avZYLmZbF6XVapmpe73oF0GWVEUO47jDnq5qWuE9ynrkc8Sn0X11VrGKcP0vtmcqh3KKqKMn5M6jWN77CBTziH6iWwS7jva2eEwHBLoB7BclNW50m9A2nsMHjNHuTpRpWNxvGvMsmXSTtjlLKhLqqcYbKf4zcR4rW2m9lzk6zhBPL92pZ5w3XNUnpUg8Ju1uwkjNS2EdF7KaNOTOxNmNrcZtZsO80APuS/imKlS6IqQsJmupxB26F1QA/oWv0si++TLNNUo167mWtlHUg1Ve4Wz+Z2pS7q0IwlFWcf8jQi4Oiwb/7g4rZ83r54u1p8sDpYxS9rdJ5CAj8lqnSr7iW7IuNC1264B3qknlYUoIvj9DXNVjZimsPcfn0Go6whAZELdhgJ1iRnxhLqmEkaLHHdQ0moJjk1lniM8I0lQhzojqtJwppEePV/ABHhCfoByVzqXE3HwBHUcWUq2U1cPfwBx81IDRqNYzF3cgmnzkfwUY6MHLQVVuPb8cYYh9A8NlqxTrNi+ayV83m6y8CwXR4dJHMP0nM7UvmlJAiFydnO7T41R6WX71IcVJhUor5fmFivXZg+LtHK1kNKtFx46IBzV7Xmm7vKde8qM93cVXz782a2uav8Xru6K8M+norksmaRb1cftg302+rz/X8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Name = _t, Code = _t, Latitude = _t, Longitude = _t, #"Target DOS" = _t, #"General Location" = _t, Order = _t, Column1 = _t, Column2 = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Name", type text}, {"Code", type text}, {"Latitude", type number}, {"Longitude", type number}, {"Target DOS", Int64.Type}, {"Order", Int64.Type}}),
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Changed Type", "Full Name", each [Code] & "-" & [Name]), {{"Full Name", type text}}),
  #"Changed column type" = Table.TransformColumnTypes(#"Added custom", {{"General Location", type text}}),
  #"Duplicated column" = Table.DuplicateColumn(#"Changed column type", "General Location", "General Location - Copy"),
  #"Extracted text before delimiter" = Table.TransformColumns(#"Duplicated column", {{"General Location - Copy", each Text.BeforeDelimiter(_, " - ", 0), type text}}),
  #"Renamed columns" = Table.RenameColumns(#"Extracted text before delimiter", {{"General Location - Copy", "Grouped Location"}}),
  #"Duplicated column 1" = Table.DuplicateColumn(#"Renamed columns", "Name", "Name - Copy"),
  #"Renamed columns 1" = Table.RenameColumns(#"Duplicated column 1", {{"Name - Copy", "Alt Name"}})
in
    #"Renamed columns 1";
shared DefaultDestination = let
  Source = Lakehouse.Contents([HierarchicalNavigation = null, CreateNavigationProperties = false, EnableFolding = false]),
  #"Navigation 1" = Source{[workspaceId = "8e2b746d-3224-4a82-8467-a2800eef337e"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[lakehouseId = "624ea251-e87f-45d7-8358-a55b3fa46385"]}[Data]
in
  #"Navigation 2";
