table Adj_Metrics_Plant
	lineageTag: 1887088d-3244-4e30-86fd-6ea4b2a78055

	column Plant
		dataType: string
		lineageTag: 8ce02c79-fe95-4931-9a3d-0560d0d85fea
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column 'Code:Plant (c1)'
		dataType: int64
		formatString: 0
		lineageTag: 89ff5f4f-044f-483f-95b5-783e3e9830c2
		summarizeBy: none
		sourceColumn: Code:Plant (c1)

		annotation SummarizationSetBy = Automatic

	column Months
		dataType: string
		lineageTag: 7e6601e7-7d05-45e8-9afb-a7cfe77b0a96
		summarizeBy: none
		sourceColumn: Months

		annotation SummarizationSetBy = Automatic

	column 'Gross Sales ADJ M(2026)'
		dataType: double
		lineageTag: 3397c77d-07ad-4c70-a77d-cd582db5c0ae
		summarizeBy: sum
		sourceColumn: Gross Sales ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Net Sales ADJ M(2026)'
		dataType: double
		lineageTag: df9b4288-ec90-457d-89cb-e5dd8a260280
		summarizeBy: sum
		sourceColumn: Net Sales ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'On Invoice Discount ADJ M(2026)'
		dataType: double
		lineageTag: d3d903a6-1134-41b1-9141-ccde5cc7f1a8
		summarizeBy: sum
		sourceColumn: On Invoice Discount ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Rebate ADJ M(2026)'
		dataType: double
		lineageTag: 1e6b051e-7b80-4ffd-837c-e9af96213a0e
		summarizeBy: sum
		sourceColumn: Total Rebate ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost of Sales ADJ M(2026)'
		dataType: double
		lineageTag: ba347b20-27f9-41d6-a3e4-15b654a4f9ef
		summarizeBy: sum
		sourceColumn: Cost of Sales ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost of RM ADJ M(2026)'
		dataType: double
		lineageTag: cdbd9500-bb76-4599-b508-df596df44e58
		summarizeBy: sum
		sourceColumn: Cost of RM ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost Of Other Materials ADJ M(2026)'
		dataType: double
		lineageTag: 9455b432-129a-4ea9-8848-12bd28562a77
		summarizeBy: sum
		sourceColumn: Cost Of Other Materials ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Variable Cost of Production ADJ M(2026)'
		dataType: double
		lineageTag: e08289c7-3792-41a5-99ae-5ffade67d564
		summarizeBy: sum
		sourceColumn: Variable Cost of Production ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fixed Costs of Production ADJ M(2026)'
		dataType: double
		lineageTag: 2041a358-58ad-4d99-988a-a55e97d1ef05
		summarizeBy: sum
		sourceColumn: Fixed Costs of Production ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Logistics ADJ M(2026)'
		dataType: double
		lineageTag: 5f27b8ca-37fe-4132-a5d3-74f28c49aec0
		summarizeBy: sum
		sourceColumn: Total Logistics ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Freight ADJ M(2026)'
		dataType: double
		lineageTag: d2003f6d-4543-4ff9-9f56-1f1bd0c93b1e
		summarizeBy: sum
		sourceColumn: Freight ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Warehousing ADJ M(2026)'
		dataType: double
		lineageTag: 0a056578-4305-4486-a291-2c88009f4d54
		summarizeBy: sum
		sourceColumn: Warehousing ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Direct contribution ADJ M(2026)'
		dataType: double
		lineageTag: 00ec6e7d-7143-40ef-bc8f-b10f3caf9c6c
		summarizeBy: sum
		sourceColumn: Direct contribution ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'EBITDA ADJ M(2026)'
		dataType: double
		lineageTag: b8ca621f-9d99-4941-bca3-5736561407fb
		summarizeBy: sum
		sourceColumn: EBITDA ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RM Weight Sold (2026)'
		dataType: double
		lineageTag: 5febd9a0-98d1-43b2-be2e-514c28131f16
		summarizeBy: sum
		sourceColumn: RM Weight Sold (2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total R&D ADJ M(2026)'
		dataType: double
		lineageTag: 5b4751a4-6b68-40a2-9c4e-d02f42231e18
		summarizeBy: sum
		sourceColumn: Total R&D ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total A&P ADJ M(2026)'
		dataType: double
		lineageTag: 7b8221cc-79e4-4f14-b413-428c9927da03
		summarizeBy: sum
		sourceColumn: Total A&P ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total C&R ADJ M(2026)'
		dataType: double
		lineageTag: 23b541ee-48dd-4e07-b5f2-cf432d155d11
		summarizeBy: sum
		sourceColumn: Total C&R ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total SG&A ADJ M(2026)'
		dataType: double
		lineageTag: aaf15bd7-862a-4f79-9d52-59a70724280e
		summarizeBy: sum
		sourceColumn: Total SG&A ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pallet QTY (2026)'
		dataType: double
		lineageTag: 38eaff04-d9c2-46d3-9add-f5f0dd6142bd
		summarizeBy: sum
		sourceColumn: Pallet QTY (2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Add back IFRS 16(2026)'
		dataType: int64
		formatString: 0
		lineageTag: e341cfc0-159b-4bf1-9052-43bce323c74b
		summarizeBy: sum
		sourceColumn: Add back IFRS 16(2026)

		annotation SummarizationSetBy = Automatic

	column 'Depreciation & Amortization ADJ M(2026)'
		dataType: double
		lineageTag: 7ffb64d9-3889-45cc-a720-4cb49c247214
		summarizeBy: sum
		sourceColumn: Depreciation & Amortization ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Currency
		dataType: string
		lineageTag: f9a0dcec-96ef-41c6-8bbf-70008aa4af07
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: f6fcf8c0-e8ad-4f2e-b0f6-dc974d3d1210
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Adj_Metrics_Plant = m
		mode: import
		queryGroup: Finance
		source =
				let
				    Source = Table.Combine({Adj_Metrics_PlantEURO, Adj_Metrics_PlantUSD}),
				    #"Added Custom" = Table.AddColumn(Source, "Date", each Date.FromText(Text.Start([Months],2)&"-01-"&Text.End([Months],2))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

