table APO_CurrentYear
	lineageTag: 2a71810d-730d-429c-bdce-9368d0f5bfb7

	column Payer
		dataType: string
		lineageTag: c7880b40-246b-473e-941a-c3749030484d
		summarizeBy: none
		sourceColumn: Payer

		annotation SummarizationSetBy = Automatic

	column 'Code:Payer (c1)'
		dataType: int64
		formatString: 0
		lineageTag: 7ac93a83-03ec-4fc2-9a19-6b08a05a29ff
		summarizeBy: none
		sourceColumn: Code:Payer (c1)

		annotation SummarizationSetBy = Automatic

	column 'SKU Level'
		dataType: string
		lineageTag: e225ac62-371c-4c0f-ac98-4ee33246a5e6
		summarizeBy: none
		sourceColumn: SKU Level

		annotation SummarizationSetBy = Automatic

	column 'Code:SKU Level (c2)'
		dataType: int64
		formatString: 0
		lineageTag: 5337ef93-f2e0-4f31-b338-84d637f70ee5
		summarizeBy: none
		sourceColumn: Code:SKU Level (c2)

		annotation SummarizationSetBy = Automatic

	column 'Market Org 2017 (SoldTo)'
		dataType: string
		lineageTag: 7de552f4-089b-4200-bbb6-fc7b11cbb631
		summarizeBy: none
		sourceColumn: Market Org 2017 (SoldTo)

		annotation SummarizationSetBy = Automatic

	column 'Code:Market Org 2017 (SoldTo) (c3)'
		dataType: int64
		formatString: 0
		lineageTag: e8378ef2-31b3-4b24-8b33-d39b6d13a631
		summarizeBy: sum
		sourceColumn: Code:Market Org 2017 (SoldTo) (c3)

		annotation SummarizationSetBy = Automatic

	column 'Profit Center Detailed'
		dataType: string
		lineageTag: d7af38ae-abb5-4910-8e61-11490fb6c42a
		summarizeBy: none
		sourceColumn: Profit Center Detailed

		annotation SummarizationSetBy = Automatic

	column 'Code:Profit Center Detailed (c4)'
		dataType: int64
		formatString: 0
		lineageTag: 53269de7-224b-4ca5-b9f6-aa3980eca83c
		summarizeBy: sum
		sourceColumn: Code:Profit Center Detailed (c4)

		annotation SummarizationSetBy = Automatic

	column Months
		dataType: string
		lineageTag: 25ec5b74-41e2-47db-b369-69ebf4b7c6fc
		summarizeBy: none
		sourceColumn: Months

		annotation SummarizationSetBy = Automatic

	column 'Committed Demand (APO)(2026)'
		dataType: int64
		formatString: 0
		lineageTag: 32f1f8ce-5b93-4f5f-b63a-0e3d27e73ac3
		summarizeBy: sum
		sourceColumn: Committed Demand (APO)(2026)

		annotation SummarizationSetBy = Automatic

	column 'Committed Gross Sales (APO)(2026)'
		dataType: double
		lineageTag: 6e7ea371-3554-49ea-b21e-b8b2e8e96173
		summarizeBy: sum
		sourceColumn: Committed Gross Sales (APO)(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Committed Net Sales (APO)(2026)'
		dataType: double
		lineageTag: 56387551-59cd-46c3-946f-366dc3315627
		summarizeBy: sum
		sourceColumn: Committed Net Sales (APO)(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Currency
		dataType: string
		lineageTag: 54cb28f5-b5c5-43bd-9076-fc5e4e609f50
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5636a594-e124-4186-94a4-0bb0bff7e351
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Segment-Region
		dataType: string
		lineageTag: b6eef3bc-4945-40e4-8cce-6b3b42f0c01f
		summarizeBy: none
		sourceColumn: Segment-Region

		annotation SummarizationSetBy = Automatic

	column 'Code Segment-Region'
		dataType: int64
		formatString: 0
		lineageTag: d3ea68da-30cd-452b-8418-5d609c6e376d
		summarizeBy: sum
		sourceColumn: Code Segment-Region

		annotation SummarizationSetBy = Automatic

	partition APO_CurrentYear = m
		mode: import
		queryGroup: APOAutoRefresh
		source =
				let
				    Source = Table.Combine({APO_CurrentYear_USD, APO_CurrentYear_Euro}),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column13"}),
				    #"Added Date" = Table.AddColumn(#"Removed Columns", "Date", each Date.FromText(Text.Start([Months],2)&"-01-"&Text.End([Months],2))),
				    #"Added Segment" = Table.AddColumn(#"Added Date", "Segment-Region", each "Americas"),
				    #"Added Custom" = Table.AddColumn(#"Added Segment", "Code Segment-Region", each 32),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Code Segment-Region", Int64.Type}, {"Segment-Region", type text}, {"Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

