table Budget_Scorecard26
	lineageTag: 37816547-179d-4163-9816-ce58d36e4740

	column Plant
		dataType: string
		lineageTag: e2f3a84b-f5e7-48a1-9902-f158042d7244
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column 'Code: Plant'
		dataType: int64
		formatString: 0
		lineageTag: 06aa654e-19cc-4a47-a16d-dcf8ffbaf2c6
		summarizeBy: none
		sourceColumn: Code: Plant

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: bbc8a7c4-f1a3-442c-b8c9-30501555f3c8
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Net Production Weight'
		dataType: double
		lineageTag: b5809539-2e7c-4d6b-821c-87bf6cb7235a
		summarizeBy: sum
		sourceColumn: Net Production Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Subcontracting Net Production'
		dataType: int64
		formatString: 0
		lineageTag: a7d98de1-5054-4b4c-adb5-3d239c17e6bd
		summarizeBy: sum
		sourceColumn: Subcontracting Net Production

		annotation SummarizationSetBy = Automatic

	column 'Direct Salary'
		dataType: double
		lineageTag: d7964c1d-bcac-41ca-953b-e362c8068c88
		summarizeBy: sum
		sourceColumn: Direct Salary

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Direct Salary per Ton'
		dataType: double
		lineageTag: e25d587a-2625-4547-8ce2-0a16242042af
		summarizeBy: sum
		sourceColumn: Direct Salary per Ton

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Electricity Cost'
		dataType: double
		lineageTag: ee6d1300-3319-488f-bcf4-d495c2f1ccf1
		summarizeBy: sum
		sourceColumn: Electricity Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Electricity per Ton'
		dataType: double
		lineageTag: 7bd88559-bafd-45a9-9f29-e02d0defb98f
		summarizeBy: sum
		sourceColumn: Electricity per Ton

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Subcontracting Costs'
		dataType: int64
		formatString: 0
		lineageTag: c6ba7597-c650-4ef0-8a0f-1711c79f7d5a
		summarizeBy: sum
		sourceColumn: Subcontracting Costs

		annotation SummarizationSetBy = Automatic

	column 'Indirect Salary'
		dataType: double
		lineageTag: 1020cba7-28f4-4ec4-bd2e-18f8488d6649
		summarizeBy: sum
		sourceColumn: Indirect Salary

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Depreciation Cost'
		dataType: double
		lineageTag: 3635f632-a49d-4a53-9818-d38f49eda45b
		summarizeBy: sum
		sourceColumn: Depreciation Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Maintenance '
		dataType: double
		lineageTag: 91f027f7-0516-49d6-b62a-8057eef95510
		summarizeBy: sum
		sourceColumn: "Maintenance "

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Other production'
		dataType: double
		lineageTag: 281f893c-700a-40bd-bd6a-eec8ea9b1dd6
		summarizeBy: sum
		sourceColumn: Other production

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Fixed costs'
		dataType: double
		lineageTag: 12681e30-094d-4153-ab36-1869f24511bd
		summarizeBy: sum
		sourceColumn: Total Fixed costs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Fixed costs per ton'
		dataType: double
		lineageTag: 70d0ff91-d41d-4e23-91db-23b74be0bc9a
		summarizeBy: sum
		sourceColumn: Total Fixed costs per ton

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Production Cost'
		dataType: double
		lineageTag: 6a4c76d9-f9e0-49bc-b0f4-d95241de64f5
		summarizeBy: sum
		sourceColumn: Total Production Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Variable Costs'
		dataType: double
		lineageTag: 14b7b647-3ccf-490c-a8b8-7a7c33027319
		summarizeBy: sum
		sourceColumn: Total Variable Costs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Forecast Version'
		dataType: string
		lineageTag: 31dc54dc-91b6-4d7a-8dca-04c2f9cd1ad7
		summarizeBy: none
		sourceColumn: Forecast Version

		annotation SummarizationSetBy = Automatic

	column Currency
		dataType: string
		lineageTag: b1a2969a-bac2-44ce-9f8e-60065381f8f6
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	partition Budget_Scorecard26 = m
		mode: import
		queryGroup: Scorecard
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\jenniferd\OneDrive - Keter Group\Dashboard Reports\Turnaround Tracker\Static Budget\Manufacturing_Scorecard_Budget_2026.xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"Plant", type text}, {"Code: Plant", Int64.Type}, {"Month", type date}, {"Net Production Weight", type number}, {"Subcontracting Net Production", Int64.Type}, {"Direct Salary", type number}, {"Direct Salary per Ton", type number}, {"Electricity Cost", type number}, {"Electricity per Ton", type number}, {"Subcontracting Costs", Int64.Type}, {"Indirect Salary", type number}, {"Depreciation Cost", type number}, {"Maintenance ", type number}, {"Other production", type number}, {"Total Fixed costs", type number}, {"Total Fixed costs per ton", type number}, {"Total Production Cost", type number}, {"Total Variable Costs", type number}, {"Forecast Version", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

