table 'Capex 2026 F&P EU'
	lineageTag: d3105458-fb2b-4267-afff-bee856bfadaf

	column 'NPD Project #'
		dataType: int64
		formatString: 0
		lineageTag: 94faa90a-b29a-468c-8495-8ce002b35afc
		summarizeBy: none
		sourceColumn: NPD Project #

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 586dbd42-5310-46d7-96b5-a804767a57b0
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: f4b65bbd-68b8-4f4c-8ccc-f29829ef63d0
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Big Category'
		dataType: string
		lineageTag: 6d18385f-91d8-457c-a0e0-14be3126aeb1
		summarizeBy: none
		sourceColumn: Big Category

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: e13da776-3e98-4316-82b3-d1e35c235c3d
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column BU
		dataType: string
		lineageTag: 7f0d6a55-8906-4e89-88ea-d44f41a26e75
		summarizeBy: none
		sourceColumn: BU

		annotation SummarizationSetBy = Automatic

	column 'Company Code'
		dataType: string
		lineageTag: b2e96dd8-50aa-4ba5-879b-89ced980580f
		summarizeBy: none
		sourceColumn: Company Code

		annotation SummarizationSetBy = Automatic

	column BA
		dataType: string
		lineageTag: aec57bcd-a8f3-4b45-8259-1507bd9dc695
		summarizeBy: none
		sourceColumn: BA

		annotation SummarizationSetBy = Automatic

	column Plant
		dataType: string
		lineageTag: 70128340-1a9e-4801-97d0-0e9d3cdb6e25
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column 'Asset Group'
		dataType: string
		lineageTag: c3802b30-3e0e-4281-a3b2-cdbad5812f43
		summarizeBy: none
		sourceColumn: Asset Group

		annotation SummarizationSetBy = Automatic

	column Reason
		dataType: string
		lineageTag: b37ff596-b253-479e-a9e0-d61278cb21b9
		summarizeBy: none
		sourceColumn: Reason

		annotation SummarizationSetBy = Automatic

	column 'Growth/Maintenance and Safety & Compliance'
		dataType: string
		lineageTag: d78b14c6-2cb9-4ea9-b05e-de2442272137
		summarizeBy: none
		sourceColumn: Growth/Maintenance and Safety & Compliance

		annotation SummarizationSetBy = Automatic

	column 'NPD / DUPLICATION…'
		dataType: string
		lineageTag: 6d7bd6cf-f49d-425f-bfe0-740d96ea4c0a
		summarizeBy: none
		sourceColumn: NPD / DUPLICATION…

		annotation SummarizationSetBy = Automatic

	column 'IT Category'
		dataType: string
		lineageTag: d6da2b34-d95b-4643-8a9d-3d36f03b6375
		summarizeBy: none
		sourceColumn: IT Category

		annotation SummarizationSetBy = Automatic

	column 'IT Class'
		dataType: string
		lineageTag: 5d997877-1f08-428c-afa7-faed79995941
		summarizeBy: none
		sourceColumn: IT Class

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: a3bb7368-2c63-48cc-91ea-1e6f361345b0
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column 'Priority 2'
		dataType: string
		lineageTag: 55f109cb-f08a-4466-94c4-ec6fa62bc5be
		summarizeBy: none
		sourceColumn: Priority 2

		annotation SummarizationSetBy = Automatic

	column 'Asset Description'
		dataType: string
		lineageTag: 6683ea3d-a8ea-40e4-b27b-4d87c6c37379
		summarizeBy: none
		sourceColumn: Asset Description

		annotation SummarizationSetBy = Automatic

	column 'Year of investment (First PO issued)'
		dataType: string
		lineageTag: 13c6d3c1-8f60-4b16-b0c4-a6ea2f07f67b
		summarizeBy: none
		sourceColumn: Year of investment (First PO issued)

		annotation SummarizationSetBy = Automatic

	column IO
		dataType: int64
		formatString: 0
		lineageTag: b2858d39-6997-4679-b07f-5e44cc5bb751
		summarizeBy: sum
		sourceColumn: IO

		annotation SummarizationSetBy = Automatic

	column 'Project started (Yes/No)'
		dataType: string
		lineageTag: a00a7fc9-6b7d-482b-9570-329bf199d31e
		summarizeBy: none
		sourceColumn: Project started (Yes/No)

		annotation SummarizationSetBy = Automatic

	column Request
		dataType: string
		lineageTag: d4a522a5-736d-45dc-bc32-9bba830c50a8
		summarizeBy: none
		sourceColumn: Request

		annotation SummarizationSetBy = Automatic

	column 'Total Investment Request'
		dataType: double
		lineageTag: 673e3ca3-3b0c-466e-93b2-20b19706487b
		summarizeBy: sum
		sourceColumn: Total Investment Request

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'EXP. 2020-2025 Request'
		dataType: double
		lineageTag: ab5b0469-8a35-4400-9a3c-6c4d60695de6
		summarizeBy: sum
		sourceColumn: EXP. 2020-2025 Request

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Exp. Q1 2026 Request'
		dataType: int64
		formatString: 0
		lineageTag: 745941f0-f0b6-469b-9de6-d73fd7ee5052
		summarizeBy: sum
		sourceColumn: Exp. Q1 2026 Request

		annotation SummarizationSetBy = Automatic

	column 'Exp. Q2 2026 Request'
		dataType: double
		lineageTag: bacf2b60-97af-48c0-a745-bd136a92ff5e
		summarizeBy: sum
		sourceColumn: Exp. Q2 2026 Request

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Exp. Q3 2026 Request'
		dataType: int64
		formatString: 0
		lineageTag: 4f0f3bc2-4ce7-4d45-8ffa-85ea5bb381f8
		summarizeBy: sum
		sourceColumn: Exp. Q3 2026 Request

		annotation SummarizationSetBy = Automatic

	column 'Exp. Q4 2026 Request'
		dataType: double
		lineageTag: 121c6988-6a74-4c38-a552-ff360b1e25f7
		summarizeBy: sum
		sourceColumn: Exp. Q4 2026 Request

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Exp. 2026 Request'
		dataType: double
		lineageTag: b8cce455-509a-4693-b02a-4a97efcbc0d3
		summarizeBy: sum
		sourceColumn: Total Exp. 2026 Request

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Exp. 2027 Request'
		dataType: int64
		formatString: 0
		lineageTag: f8f8f7d5-4017-41bf-934a-4bf6d9ea1d82
		summarizeBy: sum
		sourceColumn: Exp. 2027 Request

		annotation SummarizationSetBy = Automatic

	column 'Total Exp. Request'
		dataType: double
		lineageTag: 2a33683c-11de-426b-86e4-f0b03fbe034d
		summarizeBy: sum
		sourceColumn: Total Exp. Request

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'CF. 2020-2025 Request'
		dataType: double
		lineageTag: a59b5807-d197-4a3c-9e6d-882d4c770a51
		summarizeBy: sum
		sourceColumn: CF. 2020-2025 Request

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'CF. Q1 2026 Request'
		dataType: int64
		formatString: 0
		lineageTag: 36e93cdc-6963-4841-8dae-af5ebc5f863e
		summarizeBy: sum
		sourceColumn: CF. Q1 2026 Request

		annotation SummarizationSetBy = Automatic

	column 'CF. Q2 2026 Request'
		dataType: double
		lineageTag: d20bdb93-33b2-42b2-904d-aed7a8359e6c
		summarizeBy: sum
		sourceColumn: CF. Q2 2026 Request

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'CF. Q3 2026 Request'
		dataType: int64
		formatString: 0
		lineageTag: 66fc5f16-6bcb-4e88-8fea-ffaeed093751
		summarizeBy: sum
		sourceColumn: CF. Q3 2026 Request

		annotation SummarizationSetBy = Automatic

	column 'CF. Q4 2026 Request'
		dataType: double
		lineageTag: ce24a2d4-f784-4751-9f6a-02db78f47d0e
		summarizeBy: sum
		sourceColumn: CF. Q4 2026 Request

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total CF. 2026 Request'
		dataType: double
		lineageTag: 6554437f-1e40-4d09-99dc-7ad089680dcc
		summarizeBy: sum
		sourceColumn: Total CF. 2026 Request

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'CF. 2027 Request'
		dataType: int64
		formatString: 0
		lineageTag: c89b5034-14e0-4e29-a3c2-a9fc1a042bae
		summarizeBy: sum
		sourceColumn: CF. 2027 Request

		annotation SummarizationSetBy = Automatic

	column 'CF 2028 onwards Request'
		dataType: int64
		formatString: 0
		lineageTag: eed13d17-e041-4b62-bbbe-444fd9c1ac3d
		summarizeBy: sum
		sourceColumn: CF 2028 onwards Request

		annotation SummarizationSetBy = Automatic

	column 'Total CF Request'
		dataType: double
		lineageTag: 7e4f525f-ef33-4103-8363-b5a358df2cc1
		summarizeBy: sum
		sourceColumn: Total CF Request

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Annual Net Sales (Net)'
		dataType: double
		lineageTag: 8044ce47-7f37-425a-a92b-057d4aea148b
		summarizeBy: sum
		sourceColumn: Annual Net Sales (Net)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Annual Profit/savings'
		dataType: double
		lineageTag: dbb340b2-f86b-49d6-aa8f-9493affe4a6c
		summarizeBy: sum
		sourceColumn: Annual Profit/savings

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% Profit / Sales'
		dataType: double
		lineageTag: dd3e6ce7-6029-43a1-ab2e-7961531151b5
		summarizeBy: sum
		sourceColumn: % Profit / Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pay Back Time'
		dataType: double
		lineageTag: a6e3975d-c1c4-489a-97ca-6e29bcc6d8d4
		summarizeBy: sum
		sourceColumn: Pay Back Time

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'NS/Investment Multiplier'
		dataType: double
		lineageTag: 1378ac64-3ce4-4864-97d8-2b9e66803553
		summarizeBy: sum
		sourceColumn: NS/Investment Multiplier

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Comments
		dataType: string
		lineageTag: f634981a-1aeb-4049-968f-dbdb22804c84
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = Automatic

	partition 'Capex 2026 F&P EU' = m
		mode: import
		queryGroup: NPD
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\jenniferd\OneDrive - Keter Group\Dashboard Reports\Turnaround Tracker\NPD\Capex26_combined.xlsx"), null, true),
				    #"Capex 2026 F&P EU_Sheet" = Source{[Item="Capex 2026 F&P EU",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Capex 2026 F&P EU_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"NPD Project #", Int64.Type}, {"Region", type text}, {"Type", type text}, {"Big Category", type text}, {"Category", type text}, {"BU", type text}, {"Company Code", type text}, {"BA", type text}, {"Plant", type text}, {"Asset Group", type text}, {"Reason", type text}, {"Growth/Maintenance and Safety & Compliance", type text}, {"NPD / DUPLICATION…", type text}, {"IT Category", type any}, {"IT Class", type any}, {"Priority", type text}, {"Priority 2", type text}, {"Asset Description", type text}, {"Year of investment (First PO issued)", type text}, {"IO", Int64.Type}, {"Project started (Yes/No)", type text}, {"Request", type text}, {"Total Investment Request", type number}, {"EXP. 2020-2025 Request", type number}, {"Exp. Q1 2026 Request", Int64.Type}, {"Exp. Q2 2026 Request", type number}, {"Exp. Q3 2026 Request", Int64.Type}, {"Exp. Q4 2026 Request", type number}, {"Total Exp. 2026 Request", type number}, {"Exp. 2027 Request", Int64.Type}, {"Total Exp. Request", type number}, {"Check Inv.-Ex. Request", Int64.Type}, {"CF. 2020-2025 Request", type number}, {"CF. Q1 2026 Request", Int64.Type}, {"CF. Q2 2026 Request", type number}, {"CF. Q3 2026 Request", Int64.Type}, {"CF. Q4 2026 Request", type number}, {"Total CF. 2026 Request", type number}, {"CF. 2027 Request", Int64.Type}, {"CF 2028 onwards Request", Int64.Type}, {"Total CF Request", type number}, {"Check Ex-CF Request", Int64.Type}, {"Annual Net Sales (Net)", type number}, {"Annual Profit/savings", type number}, {"% Profit / Sales", type number}, {"Pay Back Time", type number}, {"NS/Investment Multiplier", type number}, {"Comments", type text}, {"Column49", type any}, {"Column50", type any}, {"Column51", type any}, {"Column52", type any}, {"Column53", type any}, {"Column54", type any}, {"Column55", type any}, {"Column56", type any}, {"Column57", type any}, {"Column58", type any}, {"Column59", type any}, {"Column60", type any}, {"Column61", type any}, {"Column62", type any}, {"Column63", type any}, {"Column64", type any}, {"Column65", type any}, {"Column66", type any}, {"Column67", type any}, {"Column68", type any}, {"Column69", type any}, {"Column70", type any}, {"Column71", type any}, {"Column72", type any}, {"Column73", type any}, {"Column74", type any}, {"Column75", type any}, {"Column76", type any}, {"Column77", type any}, {"Column78", type any}, {"Column79", type any}, {"Column80", type any}, {"Column81", type any}, {"Column82", type any}, {"Column83", type any}, {"Column84", type any}, {"Column85", type any}, {"Column86", type any}, {"Column87", type any}, {"Column88", type any}, {"Column89", type any}, {"Column90", type any}, {"Column91", type any}, {"Column92", type any}, {"Column93", type any}, {"Column94", type any}, {"Column95", type any}, {"Column96", type any}, {"Column97", type any}, {"Column98", type any}, {"Column99", type any}, {"Column100", type any}, {"Column101", type any}, {"Column102", type any}, {"Column103", type any}, {"Column104", type any}, {"Column105", type any}, {"Column106", type any}, {"Column107", type any}, {"Column108", type any}, {"Column109", type any}, {"Column110", type any}, {"Column111", type any}, {"Column112", type any}, {"Column113", type any}, {"Column114", type any}, {"Column115", type any}, {"Column116", type any}, {"Column117", type any}, {"Column118", type any}, {"Column119", type any}, {"Column120", type any}, {"Column121", type any}, {"Column122", type any}, {"Column123", type any}, {"Column124", type any}, {"Column125", type any}, {"Column126", type any}, {"Column127", type any}, {"Column128", type any}, {"Column129", type any}, {"Column130", type any}, {"Column131", type any}, {"Column132", type any}, {"Column133", type any}, {"Column134", type any}, {"Column135", type any}, {"Column136", type any}, {"Column137", type any}, {"Column138", type any}, {"Column139", type any}, {"Column140", type any}, {"Column141", type any}, {"Column142", type any}, {"Column143", type any}, {"Column144", type any}, {"Column145", type any}, {"Column146", type any}, {"Column147", type any}, {"Column148", type any}, {"Column149", type any}, {"Column150", type any}, {"Column151", type any}, {"Column152", type any}, {"Column153", type any}, {"Column154", type any}, {"Column155", type any}, {"Column156", type any}, {"Column157", type any}, {"Column158", type any}, {"Column159", type any}, {"Column160", type any}, {"Column161", type any}, {"Column162", type any}, {"Column163", type any}, {"Column164", type any}, {"Column165", type any}, {"Column166", type any}, {"Column167", type any}, {"Column168", type any}, {"Column169", type any}, {"Column170", type any}, {"Column171", type any}, {"Column172", type any}, {"Column173", type any}, {"Column174", type any}, {"Column175", type any}, {"Column176", type any}, {"Column177", type any}, {"Column178", type any}, {"Column179", type any}, {"Column180", type any}, {"Column181", type any}, {"Column182", type any}, {"Column183", type any}, {"Column184", type any}, {"Column185", type any}, {"Column186", type any}, {"Column187", type any}, {"Column188", type any}, {"Column189", type any}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Check Ex-CF Request", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64", "Column65", "Column66", "Column67", "Column68", "Column69", "Column70", "Column71", "Column72", "Column73", "Column74", "Column75", "Column76", "Column77", "Column78", "Column79", "Column80", "Column81", "Column82", "Column83", "Column84", "Column85", "Column86", "Column87", "Column88", "Column89", "Column90", "Column91", "Column92", "Column93", "Column94", "Column95", "Column96", "Column97", "Column98", "Column99", "Column100", "Column101", "Column102", "Column103", "Column104", "Column105", "Column106", "Column107", "Column108", "Column109", "Column110", "Column111", "Column112", "Column113", "Column114", "Column115", "Column116", "Column117", "Column118", "Column119", "Column120", "Column121", "Column122", "Column123", "Column124", "Column125", "Column126", "Column127", "Column128", "Column129", "Column130", "Column131", "Column132", "Column133", "Column134", "Column135", "Column136", "Column137", "Column138", "Column139", "Column140", "Column141", "Column142", "Column143", "Column144", "Column145", "Column146", "Column147", "Column148", "Column149", "Column150", "Column151", "Column152", "Column153", "Column154", "Column155", "Column156", "Column157", "Column158", "Column159", "Column160", "Column161", "Column162", "Column163", "Column164", "Column165", "Column166", "Column167", "Column168", "Column169", "Column170", "Column171", "Column172", "Column173", "Column174", "Column175", "Column176", "Column177", "Column178", "Column179", "Column180", "Column181", "Column182", "Column183", "Column184", "Column185", "Column186", "Column187", "Column188", "Column189", "Check Inv.-Ex. Request"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

