table Finance_2024
	lineageTag: f22423cb-ccd3-40f9-9371-59888f0786a0

	column Plant
		dataType: string
		lineageTag: 6f809b7c-b99b-4d7e-855c-1dcd0f7b96a7
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column 'Code:Plant (c1)'
		dataType: int64
		formatString: 0
		lineageTag: ff636ab7-5d01-44ad-acaf-e375d2ec40dd
		summarizeBy: none
		sourceColumn: Code:Plant (c1)

		annotation SummarizationSetBy = Automatic

	column Months
		dataType: string
		lineageTag: 80e9f4d1-6334-4b70-8ffd-42a908bb33a4
		summarizeBy: none
		sourceColumn: Months

		annotation SummarizationSetBy = Automatic

	column 'Gross Sales ADJ M(2024)'
		dataType: double
		lineageTag: a4d89c87-c40c-463d-83d2-acb15d2c4010
		summarizeBy: sum
		sourceColumn: Gross Sales ADJ M(2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'On Invoice Discount ADJ M(2024)'
		dataType: double
		lineageTag: a66130df-9f71-465c-a6f0-2bc38e3179a5
		summarizeBy: sum
		sourceColumn: On Invoice Discount ADJ M(2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Rebate ADJ M(2024)'
		dataType: double
		lineageTag: 0b2290cd-1cfd-435e-98d1-04e0fafc4586
		summarizeBy: sum
		sourceColumn: Total Rebate ADJ M(2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Net Sales ADJ M(2024)'
		dataType: double
		lineageTag: 173656ca-21d4-4cae-86a9-a9f87eb2f020
		summarizeBy: sum
		sourceColumn: Net Sales ADJ M(2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost of Sales ADJ M(2024)'
		dataType: double
		lineageTag: 41408850-6f52-4faa-a9c3-f4f10a371947
		summarizeBy: sum
		sourceColumn: Cost of Sales ADJ M(2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Logistics ADJ M(2024)'
		dataType: double
		lineageTag: 806bb0e6-34af-4884-b805-01e0938a23a4
		summarizeBy: sum
		sourceColumn: Total Logistics ADJ M(2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Freight ADJ M(2024)'
		dataType: double
		lineageTag: 08c0a804-883c-42c6-a03d-6100889c573a
		summarizeBy: sum
		sourceColumn: Freight ADJ M(2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Warehousing ADJ M(2024)'
		dataType: double
		lineageTag: 334acdfb-212d-4ee0-b068-9dd270b984fc
		summarizeBy: sum
		sourceColumn: Warehousing ADJ M(2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Direct contribution ADJ M(2024)'
		dataType: double
		lineageTag: 626d5fdc-00a7-4547-8494-b828296b0313
		summarizeBy: sum
		sourceColumn: Direct contribution ADJ M(2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total R&D ADJ M(2024)'
		dataType: double
		lineageTag: 9bb49a53-e132-481f-b2e3-a2e2ce7121ff
		summarizeBy: sum
		sourceColumn: Total R&D ADJ M(2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total A&P ADJ M(2024)'
		dataType: double
		lineageTag: 8f7fd488-1a16-4b75-8702-c7fae87ac477
		summarizeBy: sum
		sourceColumn: Total A&P ADJ M(2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total C&R ADJ M(2024)'
		dataType: double
		lineageTag: 43431f95-f9b5-4f49-8b62-3f6145da9c43
		summarizeBy: sum
		sourceColumn: Total C&R ADJ M(2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total SG&A ADJ M(2024)'
		dataType: double
		lineageTag: 8b23156c-6e86-4298-b582-d68093a815bd
		summarizeBy: sum
		sourceColumn: Total SG&A ADJ M(2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Add back IFRS 16(2024)'
		dataType: int64
		formatString: 0
		lineageTag: ea89550a-c29a-4fe2-ab34-399f1cc8aa9a
		summarizeBy: sum
		sourceColumn: Add back IFRS 16(2024)

		annotation SummarizationSetBy = Automatic

	column 'EBITDA ADJ M(2024)'
		dataType: double
		lineageTag: 24a32e3b-61f0-4032-bb43-eb1a788ead1a
		summarizeBy: sum
		sourceColumn: EBITDA ADJ M(2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RM Weight Sold (2024)'
		dataType: double
		lineageTag: ab92e312-6bf9-4bee-9e06-e5687a7cbd06
		summarizeBy: sum
		sourceColumn: RM Weight Sold (2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Net Production (RM KG)(2024)'
		dataType: double
		lineageTag: a7c66572-77fe-4483-a210-f7d829c904a8
		summarizeBy: sum
		sourceColumn: Net Production (RM KG)(2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity(2024)
		dataType: double
		lineageTag: cfc10df8-9cbb-4af6-a616-d4d27bd6d796
		summarizeBy: sum
		sourceColumn: Quantity(2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pallet QTY (2024)'
		dataType: double
		lineageTag: b4cca396-8ac6-4e6b-922e-2367e9fa196c
		summarizeBy: sum
		sourceColumn: Pallet QTY (2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Container QTY(2024)'
		dataType: double
		lineageTag: 9a5fbf93-67ee-4c9e-b087-11f50e3c3e0a
		summarizeBy: sum
		sourceColumn: Container QTY(2024)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Currency
		dataType: string
		lineageTag: 5b50154a-b463-4cfa-b71d-7ab647fc0c04
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a65f6d87-eea0-4c93-93a1-a3977113f7a9
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Finance_2024 = m
		mode: import
		queryGroup: Finance
		source =
				let
				    Source = Table.Combine({Finance_2024_EURO, Finance_2024_USD}),
				    #"Added Custom" = Table.AddColumn(Source, "Date", each Date.FromText(Text.Start([Months],2)&"-01-"&Text.End([Months],2))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

