table Finance_CurrentYear
	lineageTag: 3b35a71f-8f47-45b5-a391-be9db3f94d08

	column Plant
		dataType: string
		lineageTag: cf9ec08a-9d98-4be3-9227-ee0588330795
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column 'Code:Plant (c1)'
		dataType: int64
		formatString: 0
		lineageTag: 10553f6b-6f9f-4d8f-a2a8-f3a669876247
		summarizeBy: none
		sourceColumn: Code:Plant (c1)

		annotation SummarizationSetBy = Automatic

	column Months
		dataType: string
		lineageTag: d21bd046-ceff-4866-96b7-31a9266bb8ee
		summarizeBy: none
		sourceColumn: Months

		annotation SummarizationSetBy = Automatic

	column Currency
		dataType: string
		lineageTag: eb26931d-32d3-4cf3-a7ba-65aa7b9b8d73
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 90c8efc9-fcd2-426b-9f87-9ff6bc98d72e
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Gross Sales ADJ M(2026)'
		dataType: double
		lineageTag: d4af218d-5573-4e79-a354-c809d42c1e1a
		summarizeBy: sum
		sourceColumn: Gross Sales ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'On Invoice Discount ADJ M(2026)'
		dataType: double
		lineageTag: 3c26b30a-8a93-45a5-ba7c-b0dee349eca7
		summarizeBy: sum
		sourceColumn: On Invoice Discount ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Rebate ADJ M(2026)'
		dataType: double
		lineageTag: cc227dbc-bde9-4bd0-acd6-68b4db041a0e
		summarizeBy: sum
		sourceColumn: Total Rebate ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Net Sales ADJ M(2026)'
		dataType: double
		lineageTag: 1dc2b035-9434-47bc-b1b4-a7e8d2e1643b
		summarizeBy: sum
		sourceColumn: Net Sales ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost of Sales ADJ M(2026)'
		dataType: double
		lineageTag: 146ad0cc-1df5-426a-ad3f-56b380b27b47
		summarizeBy: sum
		sourceColumn: Cost of Sales ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Logistics ADJ M(2026)'
		dataType: double
		lineageTag: e7f4bd0a-b5cd-49fc-ab4f-7e62f2e49c82
		summarizeBy: sum
		sourceColumn: Total Logistics ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Freight ADJ M(2026)'
		dataType: double
		lineageTag: 9619610d-b8ab-4b63-b89d-842d67b64cfa
		summarizeBy: sum
		sourceColumn: Freight ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Warehousing ADJ M(2026)'
		dataType: double
		lineageTag: 2353fde1-c806-4772-8a52-18108665f59f
		summarizeBy: sum
		sourceColumn: Warehousing ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Direct contribution ADJ M(2026)'
		dataType: double
		lineageTag: 35b47cda-c094-441f-aaa2-a1d9ffedaa16
		summarizeBy: sum
		sourceColumn: Direct contribution ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total R&D ADJ M(2026)'
		dataType: double
		lineageTag: 1e5a0638-259d-4cac-a3b4-ceb60d56f572
		summarizeBy: sum
		sourceColumn: Total R&D ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total A&P ADJ M(2026)'
		dataType: double
		lineageTag: 24937932-49a7-4f01-bb9a-f3a1494894d2
		summarizeBy: sum
		sourceColumn: Total A&P ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total C&R ADJ M(2026)'
		dataType: double
		lineageTag: e13f8ff7-55e8-41cb-af5d-7066696ad61a
		summarizeBy: sum
		sourceColumn: Total C&R ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total SG&A ADJ M(2026)'
		dataType: double
		lineageTag: dd0ba7ce-1e2a-4414-b711-d4157937f45e
		summarizeBy: sum
		sourceColumn: Total SG&A ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Add back IFRS 16(2026)'
		dataType: int64
		formatString: 0
		lineageTag: d09275db-f969-419a-a329-1130c92ab060
		summarizeBy: sum
		sourceColumn: Add back IFRS 16(2026)

		annotation SummarizationSetBy = Automatic

	column 'EBITDA ADJ M(2026)'
		dataType: double
		lineageTag: e396b2ec-3cb0-43bf-b82d-a61c08639313
		summarizeBy: sum
		sourceColumn: EBITDA ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RM Weight Sold (2026)'
		dataType: double
		lineageTag: bbd9df95-75f5-484e-a648-16243fed0354
		summarizeBy: sum
		sourceColumn: RM Weight Sold (2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pallet QTY (2026)'
		dataType: double
		lineageTag: 5164ca44-d07e-4f09-b2ad-2c93c58dad08
		summarizeBy: sum
		sourceColumn: Pallet QTY (2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Net Production (RM KG)(2026)'
		dataType: double
		lineageTag: 7f1a570d-2b9d-4caf-9ac9-a73558505e3a
		summarizeBy: sum
		sourceColumn: Net Production (RM KG)(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity(2026)
		dataType: int64
		formatString: 0
		lineageTag: e0a91fec-7212-4307-875a-9b2fb045f241
		summarizeBy: sum
		sourceColumn: Quantity(2026)

		annotation SummarizationSetBy = Automatic

	column 'Container QTY(2026)'
		dataType: double
		lineageTag: 5bbb33d3-d981-4015-baa4-cf3ae54b0a2c
		summarizeBy: sum
		sourceColumn: Container QTY(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Finance_CurrentYear = m
		mode: import
		queryGroup: Finance
		source =
				let
				    Source = Table.Combine({Finance_EURO, Finance_USD}),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column24"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "Date", each Date.FromText(Text.Start([Months],2)&"-01-"&Text.End([Months],2))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

