table Inventory_CurrentYear
	lineageTag: 99f2c5a9-82e0-47f1-94a8-05b4d068b15f

	column 'Sap Material Type'
		dataType: string
		lineageTag: 0feed5d4-24fe-4813-9bdb-5593b2775d02
		summarizeBy: none
		sourceColumn: Sap Material Type

		annotation SummarizationSetBy = Automatic

	column 'Location Plant'
		dataType: string
		lineageTag: 654e273e-2cfb-466f-a558-9da77696faad
		summarizeBy: none
		sourceColumn: Location Plant

		annotation SummarizationSetBy = Automatic

	column 'Code:Location Plant (c2)'
		dataType: int64
		formatString: 0
		lineageTag: 430673db-ef71-4ee2-8ee4-080c893d7b7d
		summarizeBy: none
		sourceColumn: Code:Location Plant (c2)

		annotation SummarizationSetBy = Automatic

	column 'PC Sub Category'
		dataType: string
		lineageTag: c6ffa777-0263-45e3-9306-2a4c29e5a4f8
		summarizeBy: none
		sourceColumn: PC Sub Category

		annotation SummarizationSetBy = Automatic

	column 'Product Org'
		dataType: string
		lineageTag: 079f1a47-7c67-4ee7-85bd-f94d956459c0
		summarizeBy: none
		sourceColumn: Product Org

		annotation SummarizationSetBy = Automatic

	column 'Code:Product Org (c4)'
		dataType: int64
		formatString: 0
		lineageTag: 09705c50-bec4-4d6a-a692-57dc3186c303
		summarizeBy: sum
		sourceColumn: Code:Product Org (c4)

		annotation SummarizationSetBy = Automatic

	column 'Product Categories'
		dataType: string
		lineageTag: a23a87dc-e479-48a3-9c38-090ee8dc8f2b
		summarizeBy: none
		sourceColumn: Product Categories

		annotation SummarizationSetBy = Automatic

	column 'Code:Product Categories (c5)'
		dataType: int64
		formatString: 0
		lineageTag: dbdd87e1-10a3-46ca-a389-3cb0ceb43644
		summarizeBy: sum
		sourceColumn: Code:Product Categories (c5)

		annotation SummarizationSetBy = Automatic

	column Months
		dataType: string
		lineageTag: 1bf64c44-d30a-4597-8a5f-82e9a796cad0
		summarizeBy: none
		sourceColumn: Months

		annotation SummarizationSetBy = Automatic

	column Currency
		dataType: string
		lineageTag: 618fe4ec-95f9-4ed7-bda7-2d45c094358d
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ee208648-2a00-4ec1-9344-0fc4b0ee7616
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Budget Inventory Type'
		dataType: string
		lineageTag: b6c6eca5-4666-4c1a-bca2-8ce573d62fd8
		summarizeBy: none
		sourceColumn: Budget Inventory Type

		annotation SummarizationSetBy = Automatic

	column 'Inventory QTY'
		dataType: double
		lineageTag: 85115e12-7637-47c9-ae49-2e702fd04362
		summarizeBy: sum
		sourceColumn: Inventory QTY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RM.Weight'
		dataType: double
		lineageTag: c572d619-e0dd-40c0-9fdc-da899928eb2b
		summarizeBy: sum
		sourceColumn: RM.Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Valuation Value'
		dataType: double
		lineageTag: f66e4d0c-2b87-477f-be2d-d8c278d69bc9
		summarizeBy: sum
		sourceColumn: Valuation Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Inventory_CurrentYear = m
		mode: import
		queryGroup: Inventory
		source =
				let
				    Source = Table.Combine({Inventory_EURO, Inventory_USD}),
				    #"Added Custom" = Table.AddColumn(Source, "Date", each Date.FromText(Text.Start([Months],2)&"-01-"&Text.End([Months],2))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Date", type date}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Sap Material Type"}, Inventory_Lookup, {"Sap Material Type"}, "Inventory_Lookup", JoinKind.LeftOuter),
				    #"Expanded Inventory_Lookup" = Table.ExpandTableColumn(#"Merged Queries", "Inventory_Lookup", {"Budget Inventory Type"}, {"Inventory_Lookup.Budget Inventory Type"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Inventory_Lookup",{{"Inventory_Lookup.Budget Inventory Type", "Budget Inventory Type"}, {"Inventory QTY#(lf)(01-05/26)", "Inventory QTY"}, {"RM.Weight#(lf)(01-05/26)", "RM.Weight"}, {"Valuation Value#(lf)(01-05/26)", "Valuation Value"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

