table Manuf_Metrics_CurrentYear
	lineageTag: 8aa2d096-2dae-4e51-836b-f67d6977774e

	column Plant
		dataType: string
		lineageTag: 83d55720-e459-4739-bfdd-d8ac1c929283
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column 'Code:Plant (c1)'
		dataType: int64
		formatString: 0
		lineageTag: defe9f12-d82a-44fb-8276-215b74889366
		summarizeBy: none
		sourceColumn: Code:Plant (c1)

		annotation SummarizationSetBy = Automatic

	column Months
		dataType: string
		lineageTag: 60d08644-371b-450f-9928-ed126e10843f
		summarizeBy: none
		sourceColumn: Months

		annotation SummarizationSetBy = Automatic

	column 'Cost of Sales ADJ M(2026)'
		dataType: double
		lineageTag: 50d4763b-deb7-45b0-a09e-0cef6b1d1e6c
		summarizeBy: sum
		sourceColumn: Cost of Sales ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Manufacturing Costs ADJ M(2026)'
		dataType: double
		lineageTag: 78c5fbf2-6e71-48b3-b1ee-72abf08eb455
		summarizeBy: sum
		sourceColumn: Manufacturing Costs ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Net Production (RM KG)(2026)'
		dataType: double
		lineageTag: 41c4d2e4-5362-400a-8d56-76fc3d0469d4
		summarizeBy: sum
		sourceColumn: Net Production (RM KG)(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost of Production Materials ADJ M(2026)'
		dataType: double
		lineageTag: 107cf2ac-1d0b-49ff-8ebc-d5d51d30fa45
		summarizeBy: sum
		sourceColumn: Cost of Production Materials ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost of RM ADJ M(2026)'
		dataType: double
		lineageTag: d31b8a42-614e-4610-9e91-fb6460e2e8fd
		summarizeBy: sum
		sourceColumn: Cost of RM ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost Of Other Materials ADJ M(2026)'
		dataType: double
		lineageTag: eb87b4df-00fa-4d34-8235-799ff4b0a218
		summarizeBy: sum
		sourceColumn: Cost Of Other Materials ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Variable Cost of Production ADJ M(2026)'
		dataType: double
		lineageTag: 5b886fea-2785-481c-a8fe-fefb7392fd37
		summarizeBy: sum
		sourceColumn: Variable Cost of Production ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Electricity ADJ M(2026)'
		dataType: double
		lineageTag: 95fd1acf-d666-428c-b95c-e7731c70cde8
		summarizeBy: sum
		sourceColumn: Electricity ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Direct Labor Expenses ADJ M(2026)'
		dataType: double
		lineageTag: e1ae9ea0-dbbf-4c82-948f-7a4a482087de
		summarizeBy: sum
		sourceColumn: Direct Labor Expenses ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Subcontracting ADJ M(2026)'
		dataType: double
		lineageTag: fd1a6741-6dbc-447d-82d9-ed46231e7b09
		summarizeBy: sum
		sourceColumn: Subcontracting ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Indirect Labor Expense ADJ M(2026)'
		dataType: double
		lineageTag: 15d52f5a-64c3-4d52-8e5a-29996ec94708
		summarizeBy: sum
		sourceColumn: Indirect Labor Expense ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Depreciation & Amortization ADJ M(2026)'
		dataType: double
		lineageTag: 9329ca24-2a80-4a34-9aa8-89ecebd673ab
		summarizeBy: sum
		sourceColumn: Depreciation & Amortization ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Other Production Costs ADJ M(2026)'
		dataType: double
		lineageTag: 8e2c4875-12ad-4b5d-929f-a26832598204
		summarizeBy: sum
		sourceColumn: Other Production Costs ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fixed Costs of Production ADJ M(2026)'
		dataType: double
		lineageTag: a589e973-8940-428f-a9ca-8cf6f135b886
		summarizeBy: sum
		sourceColumn: Fixed Costs of Production ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Logistics ADJ M(2026)'
		dataType: double
		lineageTag: c9d3733a-5afa-47f3-870c-ea60989ce59e
		summarizeBy: sum
		sourceColumn: Total Logistics ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Freight ADJ M(2026)'
		dataType: double
		lineageTag: 4f8ea7db-c5f5-42a2-8fe4-c6f1db044ae0
		summarizeBy: sum
		sourceColumn: Freight ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Warehousing ADJ M(2026)'
		dataType: double
		lineageTag: 3d436004-f3c7-4da8-94b1-6232d821e9f8
		summarizeBy: sum
		sourceColumn: Warehousing ADJ M(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RM Weight Sold (2026)'
		dataType: double
		lineageTag: 222b3c26-d997-4d8a-8765-9fb42f96a6da
		summarizeBy: sum
		sourceColumn: RM Weight Sold (2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Currency
		dataType: string
		lineageTag: 1a29fc89-d0e5-48c4-89b7-54adf2b0256e
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ed60ab37-bdc8-4831-be66-423ab704318c
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Manuf_Metrics_CurrentYear = m
		mode: import
		queryGroup: Operations_ProductionMetrics
		source =
				let
				    Source = Table.Combine({Manuf_Metrics_EURO, Manuf_Metrics_USD}),
				    #"Added Custom" = Table.AddColumn(Source, "Date", each Date.FromText(Text.Start([Months],2)&"-01-"&Text.End([Months],2))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

