table Manuf_Metrics25B
	lineageTag: 037162ef-7ecc-4158-83b7-ae2110f43db7

	column Plant
		dataType: string
		lineageTag: 9dcfcf5a-956d-4e00-b21f-700cc3932618
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column Months
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4457f443-23dd-44cf-a44e-7a5735066902
		summarizeBy: none
		sourceColumn: Months

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Code: Plant'
		dataType: int64
		formatString: 0
		lineageTag: 97684c47-57da-4da4-b90a-23d6c7782411
		summarizeBy: sum
		sourceColumn: Code: Plant

		annotation SummarizationSetBy = Automatic

	column 'Cost Of Sales - Budget'
		dataType: double
		lineageTag: 78a67a13-3c38-4c8d-b803-9e9d7e257833
		summarizeBy: sum
		sourceColumn: Cost Of Sales - Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Manufactoring Costs - Budget'
		dataType: double
		lineageTag: 221674e8-d223-4ba3-99ea-81f31b396e6e
		summarizeBy: sum
		sourceColumn: Manufactoring Costs - Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost Of Production Materials - Budget'
		dataType: double
		lineageTag: c13cba4f-c67b-4970-a5c4-f573d482568d
		summarizeBy: sum
		sourceColumn: Cost Of Production Materials - Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost Of RM - Budget'
		dataType: double
		lineageTag: f570808c-e5f7-4a30-bc28-38e86fffed38
		summarizeBy: sum
		sourceColumn: Cost Of RM - Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost Of Other Materials - Budget'
		dataType: double
		lineageTag: 00735c5f-6cf0-42f8-b93e-7b2612e01d5e
		summarizeBy: sum
		sourceColumn: Cost Of Other Materials - Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Variable Cost Of Production - Budget'
		dataType: double
		lineageTag: 1c1cb745-e82d-4825-8484-f3c2c65a016c
		summarizeBy: sum
		sourceColumn: Variable Cost Of Production - Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Electric - Budget'
		dataType: double
		lineageTag: d6d4ec4e-0c34-4414-97f5-e376d4507264
		summarizeBy: sum
		sourceColumn: Electric - Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Direct Labor Expenses - Budget'
		dataType: double
		lineageTag: 894fda24-c8d6-4372-aedf-14ddcbc82165
		summarizeBy: sum
		sourceColumn: Direct Labor Expenses - Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Subcontracting - Budget'
		dataType: double
		lineageTag: efa964bc-a00b-4ebb-8e69-720b2e01497d
		summarizeBy: sum
		sourceColumn: Subcontracting - Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Indirect Labor Expense - Budget'
		dataType: double
		lineageTag: 19add0b6-f70c-439d-bbaa-ce4e4256a4f0
		summarizeBy: sum
		sourceColumn: Indirect Labor Expense - Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Other Production Costs - Budget'
		dataType: double
		lineageTag: a78b5010-a075-4b8a-98c0-a14fea596de8
		summarizeBy: sum
		sourceColumn: Other Production Costs - Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fixed Costs Of Production - Budget'
		dataType: double
		lineageTag: 0926f91a-fe2d-4467-9c00-ac6a9dc8622c
		summarizeBy: sum
		sourceColumn: Fixed Costs Of Production - Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Logistics - Budget'
		dataType: double
		lineageTag: 6b494bc1-5ba4-4077-b98c-5d699e19b21c
		summarizeBy: sum
		sourceColumn: Total Logistics - Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Freight - Budget'
		dataType: double
		lineageTag: 46e8717c-18b8-4f76-bb60-f1d2524c5ff6
		summarizeBy: sum
		sourceColumn: Total Freight - Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Warehousing - Budget'
		dataType: double
		lineageTag: 8e88a0e5-088f-49e4-871e-19918cc50a86
		summarizeBy: sum
		sourceColumn: Total Warehousing - Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RM Weight Sold - Budget'
		dataType: double
		lineageTag: be3e787d-89fc-4284-971e-bbeeb24a52ad
		summarizeBy: sum
		sourceColumn: RM Weight Sold - Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Manuf_Metrics25B = m
		mode: import
		queryGroup: 'Archive 2025'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\jenniferd\OneDrive - Keter Group\Dashboard Reports\Turnaround Tracker\Archive\ADJ_metrics_GF_global.xlsx"), null, true),
				    Manuf_Metrics25B_Table = Source{[Item="Manuf_Metrics25B",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Manuf_Metrics25B_Table,{{"Plant", type text}, {"Months", type date}, {"Code: Plant", Int64.Type}, {"Cost Of Sales - Budget", type number}, {"Manufactoring Costs - Budget", type number}, {"Cost Of Production Materials - Budget", type number}, {"Cost Of RM - Budget", type number}, {"Cost Of Other Materials - Budget", type number}, {"Variable Cost Of Production - Budget", type number}, {"Electric - Budget", type number}, {"Direct Labor Expenses - Budget", type number}, {"Subcontracting - Budget", type number}, {"Indirect Labor Expense - Budget", type number}, {"Other Production Costs - Budget", type number}, {"Fixed Costs Of Production - Budget", type number}, {"Total Logistics - Budget", type number}, {"Total Freight - Budget", type number}, {"Total Warehousing - Budget", type number}, {"RM Weight Sold - Budget", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

