table Ops_CurrentYear
	lineageTag: 33fe12b6-2ed5-4edc-8253-3e8acdfdf47f

	column 'BA Plant'
		dataType: string
		lineageTag: e3c076d4-a736-4b44-a1f4-56c07b42c672
		summarizeBy: none
		sourceColumn: BA Plant

		annotation SummarizationSetBy = Automatic

	column 'Code:BA Plant (c1)'
		dataType: int64
		formatString: 0
		lineageTag: 07458b55-f27d-4fb7-bd08-813f0b75cc6a
		summarizeBy: sum
		sourceColumn: Code:BA Plant (c1)

		annotation SummarizationSetBy = Automatic

	column 'PC Sub Category'
		dataType: string
		lineageTag: f17f6807-fd73-4bb1-b762-62e902741da0
		summarizeBy: none
		sourceColumn: PC Sub Category

		annotation SummarizationSetBy = Automatic

	column Months
		dataType: string
		lineageTag: 79d018cd-142a-419a-aef4-94b9063637a9
		summarizeBy: none
		sourceColumn: Months

		annotation SummarizationSetBy = Automatic

	column 'Net Production (RM KG)(2026)'
		dataType: double
		lineageTag: bb4d286f-04c8-4fa1-92ab-e936db4523c7
		summarizeBy: sum
		sourceColumn: Net Production (RM KG)(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RM Weight KG (Manufacture)(2026)'
		dataType: double
		lineageTag: dc5c8e59-f303-4122-82f4-f5b6a45e2d1e
		summarizeBy: sum
		sourceColumn: RM Weight KG (Manufacture)(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Prod Scrap Weight(2026)'
		dataType: double
		lineageTag: 29c9e208-a042-4140-84ec-c93558dd2d1c
		summarizeBy: sum
		sourceColumn: Prod Scrap Weight(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Work Time(2026)'
		dataType: double
		lineageTag: 10089c99-ca7a-469a-bec1-a19173d36fd7
		summarizeBy: sum
		sourceColumn: Work Time(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Lost Time(2026)'
		dataType: double
		lineageTag: 542e4315-aa4d-4f13-9926-e4f337fff330
		summarizeBy: sum
		sourceColumn: Lost Time(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'OEE (%)(2026)'
		dataType: double
		lineageTag: 7769c4d0-e9ed-4e2f-babc-b713394cfa50
		summarizeBy: sum
		sourceColumn: OEE (%)(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PEE (%)(2026)'
		dataType: double
		lineageTag: e44051bc-d9d9-49a5-b8db-6922aac7a63e
		summarizeBy: sum
		sourceColumn: PEE (%)(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Performance (%)(2026)'
		dataType: double
		lineageTag: 7d7d6807-eecc-4613-b76c-1f26c88bdb74
		summarizeBy: sum
		sourceColumn: Performance (%)(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Quality (%)(2026)'
		dataType: double
		lineageTag: 200d4722-e4d9-44e7-b6e2-0bb839184a08
		summarizeBy: sum
		sourceColumn: Quality (%)(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Availability (%)(2026)'
		dataType: double
		lineageTag: 2af6ba69-6e70-4516-a27a-07e2d7badab1
		summarizeBy: sum
		sourceColumn: Availability (%)(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Availability Pee (%)(2026)'
		dataType: double
		lineageTag: e94c2342-452a-4c47-896b-94119dd3e147
		summarizeBy: sum
		sourceColumn: Availability Pee (%)(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Direct Salary(2026)'
		dataType: double
		lineageTag: 9366e73d-41a4-4bba-8c38-33b3d0bc6767
		summarizeBy: sum
		sourceColumn: Direct Salary(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Indir Salary(2026)'
		dataType: double
		lineageTag: 15b0bce1-0bc9-4658-8283-407a50d2a4f6
		summarizeBy: sum
		sourceColumn: Indir Salary(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Net Production(2026)'
		dataType: int64
		formatString: 0
		lineageTag: 55254d22-9d35-4d82-a105-66c3cdf926d4
		summarizeBy: sum
		sourceColumn: Net Production(2026)

		annotation SummarizationSetBy = Automatic

	column 'Gross Production(2026)'
		dataType: int64
		formatString: 0
		lineageTag: 2003cdd6-5ae6-4fe7-91a5-e386d38edaa9
		summarizeBy: sum
		sourceColumn: Gross Production(2026)

		annotation SummarizationSetBy = Automatic

	column 'PP Stop(2026)'
		dataType: double
		lineageTag: 2bfe1a6e-b462-43b9-b482-019b9b484660
		summarizeBy: sum
		sourceColumn: PP Stop(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Time (Sec.) / KG(2026)'
		dataType: double
		lineageTag: bb9d18c1-5091-467d-b7fa-2200d19255d5
		summarizeBy: sum
		sourceColumn: Time (Sec.) / KG(2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Currency
		dataType: string
		lineageTag: e1943e9f-ccb3-44d9-a095-0b5f08f009b5
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0f960786-e0d7-4912-8cbf-bbe5d31d1ed1
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Total Seconds'
		dataType: double
		lineageTag: 1acae0ac-6351-45b0-99fb-4a7cfc50f162
		summarizeBy: sum
		sourceColumn: Total Seconds

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Ops_CurrentYear = m
		mode: import
		queryGroup: Operations_ProductionMetrics
		source =
				let
				    Source = Table.Combine({OPS_EURO, OPS_USD}),
				    #"Added Custom" = Table.AddColumn(Source, "Date", each Date.FromText(Text.Start([Months],2)&"-01-"&Text.End([Months],2))),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Total Seconds", each [#"Time (Sec.) / KG#(lf)(2026)"]*[#"RM Weight KG (Manufacture)#(lf)(2026)"]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom1",{{"Date", type date}, {"Total Seconds", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

