table Product_Table_GF_Global
	lineageTag: 6875869e-a889-44ed-8cf7-15e9f89a1ca6

	column 'SKU Level'
		dataType: string
		lineageTag: d5d9920a-3de2-4ed3-a6d6-9d8fc76e54da
		summarizeBy: none
		sourceColumn: SKU Level

		annotation SummarizationSetBy = Automatic

	column 'Code:SKU Level (c1)'
		dataType: int64
		formatString: 0
		lineageTag: b5620438-cf55-408f-be8d-6b9b98b29e41
		summarizeBy: none
		sourceColumn: Code:SKU Level (c1)

		annotation SummarizationSetBy = Automatic

	column 'SKU Group'
		dataType: string
		lineageTag: fed6e219-1778-4793-9f7c-934d3efc2f65
		summarizeBy: none
		sourceColumn: SKU Group

		annotation SummarizationSetBy = Automatic

	column 'Code:SKU Group (c2)'
		dataType: int64
		formatString: 0
		lineageTag: 3a632821-9462-429d-953e-4839b8d7e3bb
		summarizeBy: none
		sourceColumn: Code:SKU Group (c2)

		annotation SummarizationSetBy = Automatic

	column 'Product Categories'
		dataType: string
		lineageTag: 5e0aca0c-d874-40c4-820e-8383da0a9a42
		summarizeBy: none
		sourceColumn: Product Categories

		annotation SummarizationSetBy = Automatic

	column 'Code:Product Categories (c3)'
		dataType: int64
		formatString: 0
		lineageTag: 9291c5be-a843-4615-94ba-c2482480ef29
		summarizeBy: sum
		sourceColumn: Code:Product Categories (c3)

		annotation SummarizationSetBy = Automatic

	column 'Product Line'
		dataType: string
		lineageTag: 4958ef60-4c30-4397-914d-5a5a6c6bcd5b
		summarizeBy: none
		sourceColumn: Product Line

		annotation SummarizationSetBy = Automatic

	column 'Code:Product Line (c4)'
		dataType: int64
		formatString: 0
		lineageTag: 8416b6ad-bd4d-4734-be65-b2ba9db61dc1
		summarizeBy: sum
		sourceColumn: Code:Product Line (c4)

		annotation SummarizationSetBy = Automatic

	column 'Item First Birth Date'
		dataType: int64
		formatString: 0
		lineageTag: 90a01a9d-3c6d-47ed-8f74-bfddff8adfd3
		summarizeBy: sum
		sourceColumn: Item First Birth Date

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: 09de9ec4-7333-49f8-8cc8-0da3a86fd1b8
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column EAN/UPC
		dataType: int64
		formatString: 0
		lineageTag: e308fbd4-b446-440a-8f99-bcca8a03e4ac
		summarizeBy: sum
		sourceColumn: EAN/UPC

		annotation SummarizationSetBy = Automatic

	column 'Code:Brand (c6)'
		dataType: int64
		formatString: 0
		lineageTag: 525f631a-be3b-451b-8c4d-1a5d1cb09d2a
		summarizeBy: sum
		sourceColumn: Code:Brand (c6)

		annotation SummarizationSetBy = Automatic

	column 'Product Type'
		dataType: string
		lineageTag: 9bcc7fa0-bdd2-4a9e-ae7d-f94f65747f89
		summarizeBy: none
		sourceColumn: Product Type

		annotation SummarizationSetBy = Automatic

	column 'Code:Product Type (c7)'
		dataType: int64
		formatString: 0
		lineageTag: 76b919a2-cff0-4f51-9ff6-1fe7b24c7611
		summarizeBy: sum
		sourceColumn: Code:Product Type (c7)

		annotation SummarizationSetBy = Automatic

	column 'Product Type Detailed'
		dataType: string
		lineageTag: 6e98d84a-2349-4702-9a5a-9475eeed147b
		summarizeBy: none
		sourceColumn: Product Type Detailed

		annotation SummarizationSetBy = Automatic

	column 'Code:Product Type Detailed (c8)'
		dataType: int64
		formatString: 0
		lineageTag: 52431754-4c30-45a2-be02-d72952b9a7ef
		summarizeBy: sum
		sourceColumn: Code:Product Type Detailed (c8)

		annotation SummarizationSetBy = Automatic

	column 'Price Group'
		dataType: string
		lineageTag: 588667c8-c002-4e17-8c0d-b2536fad05bf
		summarizeBy: none
		sourceColumn: Price Group

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: 46c02924-1fda-42cf-b01c-15c8c12fee04
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column 'Code:Color (c4)'
		dataType: int64
		formatString: 0
		lineageTag: c7475352-6271-42fe-8c98-5c21c4938cc7
		summarizeBy: sum
		sourceColumn: Code:Color (c4)

		annotation SummarizationSetBy = Automatic

	column BU
		dataType: string
		lineageTag: a5582b8e-d99c-429d-8014-eb4edc7f5619
		summarizeBy: none
		sourceColumn: BU

		annotation SummarizationSetBy = Automatic

	column '2026 NPD'
		dataType: string
		lineageTag: b500c4fd-d299-495d-adae-724c00e75488
		summarizeBy: none
		sourceColumn: 2026 NPD

		annotation SummarizationSetBy = Automatic

	column DecoCoat
		dataType: string
		lineageTag: ab0f2ffc-49ec-49cb-b3ed-1875ef6e6eae
		summarizeBy: none
		sourceColumn: DecoCoat

		annotation SummarizationSetBy = Automatic

	column 'NPD Project #'
		dataType: string
		lineageTag: 4bf47b3d-047a-4206-a9eb-c7eb6dc580d2
		summarizeBy: none
		sourceColumn: NPD Project #

		annotation SummarizationSetBy = Automatic

	column 'SKU Code_Desc' = Product_Table_GF_Global[Code:SKU Level (c1)]&" "&Product_Table_GF_Global[SKU Level]
		lineageTag: f775ec06-10e8-481e-b320-90f59898889a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Product_Table_GF_Global = m
		mode: import
		queryGroup: 'Refresh Dimensions'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\jenniferd\OneDrive - Keter Group\Dashboard Reports\Turnaround Tracker\Refreshed Dimensions\ProductTable_GF_Global.xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"SKU Level", type text}, {"Code:SKU Level (c1)", Int64.Type}, {"SKU Group", type text}, {"Code:SKU Group (c2)", Int64.Type}, {"Product Categories", type text}, {"Code:Product Categories (c3)", Int64.Type}, {"Product Line", type text}, {"Code:Product Line (c4)", Int64.Type}, {"Item First Birth Date", Int64.Type}, {"Brand", type text}, {"EAN/UPC", Int64.Type}, {"Code:Brand (c6)", Int64.Type}, {"Product Type", type text}, {"Code:Product Type (c7)", Int64.Type}, {"Product Type Detailed", type text}, {"Code:Product Type Detailed (c8)", Int64.Type}, {"Price Group", type text}, {"Color", type text}, {"Code:Color (c4)", Int64.Type}, {"BU", type text}, {"2026 NPD", type any},  {"DecoCoat", type any}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

