[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "Dim Location Dimension 2_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared #"Dim Location Dimension 2" = let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("nZhtU+M4DID/iqcf7nZnSCa2Eyf+GEK37dE3SBeO29kPpg2QISQ7abt7++9Ptpw2LS2Um+mQvviRZEmWZL596/givCD9r+SHqldlVnfOOvBFHx6cuZT6At45EXWp4Aze2tf3MwOm+2B6IninwWkLvLOgF3nSgp6ke2A8n2flSi8UMoaHH7iBR836kLuBCP299S9Znc9VCZrmz3n5aMjIaApcxkJqNHlu5HO6S57X6qXItQoRnp9gWdJPyXRyPSMOoR5DboRcGIrAWChdyelWD/VekcyS3ZPJ2bDNxchJGgV2Zx7bM/SiP8S1Pq5lgttNMa4hqv/gIikbwhiIGGviGzbhNdFlW8xap7G7+PoCMW61SbHVpi1oaYsM9mWUk2H1mC9X+XyJkU5OiHSvqO4zQiPuUXJeVwYMe/rB3cgsdiiNXIZ2+1rttSrnT9V2n3/Ff78KxEBL8FzOzRfabhEE4a7qy3EMyHlWvFQ2N6MUM4wHUeMlT0b0EJY85aW1Vm+T+66HysHc0BVRJBtzm5XWWsS7i3xZlcjrpPE9N6CoNPRdn7KDSvvVerlqMB1XJt1QeMZLEswWEIsD2DAv51VRbshrVEi9AFMoAHs9foBMnrK6/v0zL4oMyfGJZBrfuORicN1NbPbRJvuCoMkjPzywx1T9dMlgRD6xzwhennCGNxqnyXCbAncfJk24gPznoyQzNRPIK7tNX9LOsSK6QwrPQ/KUKmodpMpSaTjAmFydbm08Hsd9kvyRoM6Lj5K3/RTJ4WmkA6qc7rx6eUFsusmCrXf0W29TTJi3YXtZVT/mqilhsNO0wd9oUQdI/wPkNG7b2zsRg2A4m+7x9QTfjPICTiMczcHLj6q2jVGngM91HTCHC5pHFO6Xy0l3SCY/s3qZKVtkrzq2yDJjIxRZEQaWgtWHQNDLEJ4h7Pu29EDNpcIUWu9N/BZx/fAlOEUY3ZRx6CpcHFI+ghpbZ6og081+p50j7SHY0LYlwbzx/ARViDhtf42O+WvPdkhfMrlpN/ixjWvTG6g4lIRbrikpX44d7y2LJB7SJ7NZkmD2DjtHSuAWtttNf9RZNlN5QWYKklEhb+am0GUBk+hsBnHzece2GQOtAOpsWs1Wzk32aPMFhyIBhksUQwOImekbx8TM+hfghFH2bz63HU97noVuwD0TdyldH9uA10rVr6kTjy+61+lkPBg7QGHSmAf0EIlegHEueg0mk3SWTMh1dxonl4NxT+NTxKeIi8h0PWiWNDygeThJSTzudYfd1E1ijV8ibh6HRos9AU3Nc3uG7iPdDMkHE6Chb7JVVqvyzyVJVF3ncGgwexILo2rNykYxhh9m2cM8uVP1AoVMGiGbMU7u5hC3M2allis4bvGqUCWMZGQyz5Tu/zMQvcxXJCTmoBvrHaFjELZ+dYj+JHdEjbNfD9W6XIDAxRnYVqqFaiHUJ8IMPWZ7AXelUbArFRY5uAynxgSuBfVbZjJq7fRdkzBcvpJpZqXQ1tWFc1yU3qTpN4450HtS9K8Czw2YBN9VD6SX34N1K1W3lnLsu2aT7gHHmd8DI2gMx/+JxA/6LnNGykzVJC4e4WqjnNm6zJd523++qcmRq3cDNVUe2KlZ4u84bpQtckgXWAKbJWmmyKfq4QFGvvvf6nNbutw6ESoHtKTXwcE1OM2vV+s6I9O6Wqznq9xMjoe+g1QUXDDJw8gTwjO3CTNAhxH3AxZwHvm0qS19lT/oHWOam08kXVW1esyaX1ufQXTEwhBqjKQ+C6MINyAlhemYB4xqdQIzfiub4a1iXTzo+KUrlwzVrzor59lu7ptMhbplsl/onklfH4EmV/Ec3GZL8HR5PFf1CQixvpgsM214P/83qa9z1SbIW8lvYiKPpn5jYrhX8XvwpvxVVQssXKZsSFdg6YHyzxvHvdk3ukWh7rOiQCGDzm7bxHx5V8jYbK56tncIc7GE5mfKt3hDQmunHjp284KLyfy5qbe76+TRdfFCvSzJlxwO3lNmyqnpHLoXiVBiPYW7TcCYreYG2KXP13mxcIlA2t7cIgHDnsUhUaV4D6eIX1jt3LPzJWj3/fdxjvi51R4IFm60S/mu8T7iSYPLoPmnA5OB5Efxqc5SMzkCHTeeE+ZgWs8F9Ch9OzANvOVye4fUINz+j4KDktjwoman9ekjBljzyVTZ2DvnRTV/xkz4P4KuYivn6lRnfP8P", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Name = _t, Code = _t, Latitude = _t, Longitude = _t, #"Target DOS" = _t, #"General Location" = _t, Order = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Name", type text}, {"Code", type text}, {"Latitude", type number}, {"Longitude", type number}, {"Target DOS", Int64.Type}, {"Order", Int64.Type}}),
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Changed Type", "Full Name", each [Code] & "-" & [Name]), {{"Full Name", type text}}),
  #"Changed column type" = Table.TransformColumnTypes(#"Added custom", {{"General Location", type text}})
in
    #"Changed column type";
shared #"Dim Location Dimension 2_DataDestination" = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = null, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "8e2b746d-3224-4a82-8467-a2800eef337e"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "624ea251-e87f-45d7-8358-a55b3fa46385"]}[Data],
  TableNavigation = Navigation_2{[Id = "Dim Location Dimension 2", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
