table 'Master Page Gallery'
	lineageTag: 4d480185-6da5-49c9-b579-21db9931634d

	column FileSystemObjectType
		dataType: string
		lineageTag: 18ce80c5-5121-4ca5-893d-bea87943daeb
		summarizeBy: none
		sourceColumn: FileSystemObjectType

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: string
		lineageTag: 33b9030c-1a96-4eeb-b71b-4641a0cbfe7c
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column ServerRedirectedEmbedUri
		dataType: string
		lineageTag: 4c1b4643-5cfd-4cb3-80ff-8cebbe4083f9
		summarizeBy: none
		sourceColumn: ServerRedirectedEmbedUri

		annotation SummarizationSetBy = Automatic

	column ServerRedirectedEmbedUrl
		dataType: string
		lineageTag: d227769b-1e66-46ac-a3ff-23c98014b3b4
		summarizeBy: none
		sourceColumn: ServerRedirectedEmbedUrl

		annotation SummarizationSetBy = Automatic

	column ContentTypeId
		dataType: string
		lineageTag: b2c2f7af-2e09-4b0f-971a-ee84fd863dc1
		summarizeBy: none
		sourceColumn: ContentTypeId

		annotation SummarizationSetBy = Automatic

	column OData__ColorTag
		dataType: string
		lineageTag: bafb2ea2-c073-4931-9ffb-4c5200f0cbfb
		summarizeBy: none
		sourceColumn: OData__ColorTag

		annotation SummarizationSetBy = Automatic

	column ComplianceAssetId
		dataType: string
		lineageTag: f31f1a2b-6980-41a1-acbd-acb43d140854
		summarizeBy: none
		sourceColumn: ComplianceAssetId

		annotation SummarizationSetBy = Automatic

	column MasterPageDescription
		dataType: string
		lineageTag: c7e3f06c-31d5-4d3a-8a41-07bdfd3523ef
		summarizeBy: none
		sourceColumn: MasterPageDescription

		annotation SummarizationSetBy = Automatic

	column UIVersion
		dataType: string
		lineageTag: 62a7e1f1-5354-4562-8d00-a65aa8926a8c
		summarizeBy: none
		sourceColumn: UIVersion

		annotation SummarizationSetBy = Automatic

	column DefaultCssFile
		dataType: string
		lineageTag: 0bd60266-8823-41fa-bbe4-64940f10fcc8
		summarizeBy: none
		sourceColumn: DefaultCssFile

		annotation SummarizationSetBy = Automatic

	column DisplayTemplateJSTemplateHidden
		dataType: string
		lineageTag: e537426b-2199-40ae-9ad8-bbf6b97e6975
		summarizeBy: none
		sourceColumn: DisplayTemplateJSTemplateHidden

		annotation SummarizationSetBy = Automatic

	column DisplayTemplateJSTargetControlType
		dataType: string
		lineageTag: 250a58de-0961-4ba4-bf07-3c669d004a48
		summarizeBy: none
		sourceColumn: DisplayTemplateJSTargetControlType

		annotation SummarizationSetBy = Automatic

	column DisplayTemplateJSIconUrl
		dataType: string
		lineageTag: 64f04865-5794-4a0c-a4ea-0cdd60261b93
		summarizeBy: none
		sourceColumn: DisplayTemplateJSIconUrl

		annotation SummarizationSetBy = Automatic

	column DisplayTemplateJSTemplateType
		dataType: string
		lineageTag: 816dc6f1-5c8d-459c-9589-20a21306d554
		summarizeBy: none
		sourceColumn: DisplayTemplateJSTemplateType

		annotation SummarizationSetBy = Automatic

	column DisplayTemplateJSTargetScope
		dataType: string
		lineageTag: b08676fa-3270-49fe-bd83-9bf0cbc59c35
		summarizeBy: none
		sourceColumn: DisplayTemplateJSTargetScope

		annotation SummarizationSetBy = Automatic

	column DisplayTemplateJSTargetListTemplate
		dataType: string
		lineageTag: d7877a6a-8ecb-4b5a-a71c-89d8bbc2d2fd
		summarizeBy: none
		sourceColumn: DisplayTemplateJSTargetListTemplate

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: f18d08e6-b5c1-4828-8126-51dd4cda9fdd
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column TemplateHidden
		dataType: string
		lineageTag: 1f6903ae-7e68-43b8-b51f-f8ff1e646e48
		summarizeBy: none
		sourceColumn: TemplateHidden

		annotation SummarizationSetBy = Automatic

	column TargetControlType
		dataType: string
		lineageTag: ffff5198-c51b-46d1-b081-762aba00ae5a
		summarizeBy: none
		sourceColumn: TargetControlType

		annotation SummarizationSetBy = Automatic

	column CrawlerXSLFile
		dataType: string
		lineageTag: 63314dc6-8b5a-46b4-a5d9-2407b46be22a
		summarizeBy: none
		sourceColumn: CrawlerXSLFile

		annotation SummarizationSetBy = Automatic

	column DisplayTemplateLevel
		dataType: string
		lineageTag: f6b2f09c-85bd-4dd5-bc1d-97084c398940
		summarizeBy: none
		sourceColumn: DisplayTemplateLevel

		annotation SummarizationSetBy = Automatic

	column ManagedPropertyMapping
		dataType: string
		lineageTag: 1f2b2602-5e56-4465-8d93-fe667e316045
		summarizeBy: none
		sourceColumn: ManagedPropertyMapping

		annotation SummarizationSetBy = Automatic

	column CompatibleSearchDataTypes
		dataType: string
		lineageTag: a5353de1-23e0-4b10-b555-383a4252d517
		summarizeBy: none
		sourceColumn: CompatibleSearchDataTypes

		annotation SummarizationSetBy = Automatic

	column CompatibleManagedProperties
		dataType: string
		lineageTag: da1fda40-1c76-4950-b793-fadaea60884a
		summarizeBy: none
		sourceColumn: CompatibleManagedProperties

		annotation SummarizationSetBy = Automatic

	column 'ID.1'
		dataType: string
		lineageTag: c0a44e96-d338-476f-a121-fd219a0763cb
		summarizeBy: none
		sourceColumn: ID.1

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: string
		lineageTag: 8434f187-ae21-4f11-a224-db0ab3490214
		summarizeBy: none
		sourceColumn: Created

		annotation SummarizationSetBy = Automatic

	column AuthorId
		dataType: string
		lineageTag: 3730818a-1fe5-4259-8148-4c343483882c
		summarizeBy: none
		sourceColumn: AuthorId

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: string
		lineageTag: 34e00106-1e40-4dfd-81aa-03e92cd9cef9
		summarizeBy: none
		sourceColumn: Modified

		annotation SummarizationSetBy = Automatic

	column EditorId
		dataType: string
		lineageTag: 19b08d55-917a-4884-87c3-7ef9d3ae6a4e
		summarizeBy: none
		sourceColumn: EditorId

		annotation SummarizationSetBy = Automatic

	column OData__CopySource
		dataType: string
		lineageTag: dd66a02e-cbbb-4d06-a042-73ddeece0e21
		summarizeBy: none
		sourceColumn: OData__CopySource

		annotation SummarizationSetBy = Automatic

	column CheckoutUserId
		dataType: string
		lineageTag: a08edbaf-7728-44aa-a933-5a3a54c1bc62
		summarizeBy: none
		sourceColumn: CheckoutUserId

		annotation SummarizationSetBy = Automatic

	column OData__UIVersionString
		dataType: string
		lineageTag: f49d4da9-abc5-4403-a709-8afe3fc645bd
		summarizeBy: none
		sourceColumn: OData__UIVersionString

		annotation SummarizationSetBy = Automatic

	column GUID
		dataType: string
		lineageTag: d1a7dbf2-7973-4781-af24-73fc5951eb8b
		summarizeBy: none
		sourceColumn: GUID

		annotation SummarizationSetBy = Automatic

	partition 'Master Page Gallery' = m
		mode: import
		source =
				let
				    Source = SharePoint.Tables("https://keteronline.sharepoint.com/sites/QAContainer/", [ApiVersion = 15]),
				    #"1835c5fc-e8fa-42dd-a48c-5fc4bff14753" = Source{[Id="1835c5fc-e8fa-42dd-a48c-5fc4bff14753"]}[Items],
				    #"Renamed Columns" = Table.RenameColumns(#"1835c5fc-e8fa-42dd-a48c-5fc4bff14753",{{"ID", "ID.1"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

