table 'Savannah - Project Tracker'
	lineageTag: 7b36c3ef-629c-4d5d-838b-beafb978529c

	column FileSystemObjectType
		dataType: string
		lineageTag: 676de30d-6f9d-4e83-aac6-34416e255711
		summarizeBy: none
		sourceColumn: FileSystemObjectType

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: string
		lineageTag: 1e7a8096-571c-4f74-8c75-b2a7410ae9b6
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column ServerRedirectedEmbedUri
		dataType: string
		lineageTag: f4d1f599-b68a-47d0-9d9b-1ce69041bb89
		summarizeBy: none
		sourceColumn: ServerRedirectedEmbedUri

		annotation SummarizationSetBy = Automatic

	column ServerRedirectedEmbedUrl
		dataType: string
		lineageTag: 5d572ff4-806d-4dee-9783-066a96ef4fff
		summarizeBy: none
		sourceColumn: ServerRedirectedEmbedUrl

		annotation SummarizationSetBy = Automatic

	column ContentTypeId
		dataType: string
		lineageTag: 549891e3-2033-416e-8334-0df3e9f79003
		summarizeBy: none
		sourceColumn: ContentTypeId

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: bbb664ea-5214-4c7d-9688-a39fe9fc641f
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column OData__ColorTag
		dataType: string
		lineageTag: 4584409b-302f-4b2c-9ca5-4975a01af6d6
		summarizeBy: none
		sourceColumn: OData__ColorTag

		annotation SummarizationSetBy = Automatic

	column ComplianceAssetId
		dataType: string
		lineageTag: 1cb49fe0-96de-47b1-869b-fa395d47b152
		summarizeBy: none
		sourceColumn: ComplianceAssetId

		annotation SummarizationSetBy = Automatic

	column field_4
		dataType: string
		lineageTag: ebe5db80-ba10-4e0f-9701-2e950661fb3a
		summarizeBy: none
		sourceColumn: field_4

		annotation SummarizationSetBy = Automatic

	column field_5
		dataType: string
		lineageTag: e2a7e38a-2117-42c1-9b3d-f16e433ed4c7
		summarizeBy: none
		sourceColumn: field_5

		annotation SummarizationSetBy = Automatic

	column field_6
		dataType: string
		lineageTag: 616006b9-57ca-4fce-94a1-44668acd9a78
		summarizeBy: none
		sourceColumn: field_6

		annotation SummarizationSetBy = Automatic

	column field_7
		dataType: string
		lineageTag: 79947a9d-0a2b-4f72-a2f8-eab4d441ffd5
		summarizeBy: none
		sourceColumn: field_7

		annotation SummarizationSetBy = Automatic

	column field_8
		dataType: string
		lineageTag: 4fcfe60e-6d9d-4723-85a1-04f4c414fbc3
		summarizeBy: none
		sourceColumn: field_8

		annotation SummarizationSetBy = Automatic

	column field_9
		dataType: string
		lineageTag: 77614eee-5c08-476e-b93e-e1c2dce3a7ec
		summarizeBy: none
		sourceColumn: field_9

		annotation SummarizationSetBy = Automatic

	column field_10
		dataType: string
		lineageTag: f1a4cdff-803d-4589-9f8b-a0de18cead03
		summarizeBy: none
		sourceColumn: field_10

		annotation SummarizationSetBy = Automatic

	column field_11
		dataType: string
		lineageTag: fc1daf8c-6b1f-4a2f-b129-987cee97e3fa
		summarizeBy: none
		sourceColumn: field_11

		annotation SummarizationSetBy = Automatic

	column field_12
		dataType: string
		lineageTag: 60a69333-3fd8-43c3-aeea-467451526924
		summarizeBy: none
		sourceColumn: field_12

		annotation SummarizationSetBy = Automatic

	column field_13
		dataType: string
		lineageTag: 0af479a3-ee9a-4b86-99e6-c6eb82180b07
		summarizeBy: none
		sourceColumn: field_13

		annotation SummarizationSetBy = Automatic

	column field_14
		dataType: string
		lineageTag: 5718ed6c-335a-4d6a-8dc7-0e5df4044d36
		summarizeBy: none
		sourceColumn: field_14

		annotation SummarizationSetBy = Automatic

	column field_15
		dataType: string
		lineageTag: d73eccea-63f8-46e5-93a7-6efa39e7bc84
		summarizeBy: none
		sourceColumn: field_15

		annotation SummarizationSetBy = Automatic

	column field_16
		dataType: string
		lineageTag: a4ef4863-5319-4911-81fb-1146f9f0389e
		summarizeBy: none
		sourceColumn: field_16

		annotation SummarizationSetBy = Automatic

	column field_17
		dataType: string
		lineageTag: b3617e6f-ddd6-4bc2-8558-f62d49caaf53
		summarizeBy: none
		sourceColumn: field_17

		annotation SummarizationSetBy = Automatic

	column field_18
		dataType: string
		lineageTag: 41635758-002c-472f-b52c-9307b9798422
		summarizeBy: none
		sourceColumn: field_18

		annotation SummarizationSetBy = Automatic

	column field_19
		dataType: string
		lineageTag: 383d34ca-ee1d-41cc-966f-b4bdd928091e
		summarizeBy: none
		sourceColumn: field_19

		annotation SummarizationSetBy = Automatic

	column field_20
		dataType: string
		lineageTag: ee6594a1-4190-4b7e-86d5-064d1f0a243a
		summarizeBy: none
		sourceColumn: field_20

		annotation SummarizationSetBy = Automatic

	column ItemNumId
		dataType: string
		lineageTag: dc54d125-3f89-4d73-90cb-fab8e6e57e4c
		summarizeBy: none
		sourceColumn: ItemNumId

		annotation SummarizationSetBy = Automatic

	column LineType
		dataType: string
		lineageTag: 1e1bd647-e081-4293-bcc7-746cb5edd56b
		summarizeBy: none
		sourceColumn: LineType

		annotation SummarizationSetBy = Automatic

	column 'ID.1'
		dataType: string
		lineageTag: ac2caaf6-2750-416a-bac3-3ee9e6f0b750
		summarizeBy: none
		sourceColumn: ID.1

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: string
		lineageTag: 6194e893-29f8-43fd-a4fc-5ae9675f20f9
		summarizeBy: none
		sourceColumn: Modified

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: string
		lineageTag: 9fdcacaa-2169-4454-a2c1-feb6231e31d9
		summarizeBy: none
		sourceColumn: Created

		annotation SummarizationSetBy = Automatic

	column AuthorId
		dataType: string
		lineageTag: 5f6d5fe9-c24a-4eaa-8f9e-14c7dd6cde83
		summarizeBy: none
		sourceColumn: AuthorId

		annotation SummarizationSetBy = Automatic

	column EditorId
		dataType: string
		lineageTag: 2ca18f9c-6baa-41f2-9816-2f581aa49526
		summarizeBy: none
		sourceColumn: EditorId

		annotation SummarizationSetBy = Automatic

	column OData__UIVersionString
		dataType: string
		lineageTag: 5858f1f6-1e4b-4929-8e58-19b2d1e933e2
		summarizeBy: none
		sourceColumn: OData__UIVersionString

		annotation SummarizationSetBy = Automatic

	column Attachments
		dataType: string
		lineageTag: 8c23c40c-38b4-4568-9c8f-dbb05e96e511
		summarizeBy: none
		sourceColumn: Attachments

		annotation SummarizationSetBy = Automatic

	column GUID
		dataType: string
		lineageTag: 25e84cde-388b-424d-95f7-d99ba7c65e53
		summarizeBy: none
		sourceColumn: GUID

		annotation SummarizationSetBy = Automatic

	partition 'Savannah - Project Tracker' = m
		mode: import
		source =
				let
				    Source = SharePoint.Tables("https://keteronline.sharepoint.com/sites/QAContainer/", [ApiVersion = 15]),
				    #"f21fefee-9cf0-4e4c-8578-3c9e9ec3957b" = Source{[Id="f21fefee-9cf0-4e4c-8578-3c9e9ec3957b"]}[Items],
				    #"Renamed Columns" = Table.RenameColumns(#"f21fefee-9cf0-4e4c-8578-3c9e9ec3957b",{{"ID", "ID.1"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

