table 'Savannah - Container-Defects'
	lineageTag: 9222577c-4794-4390-8d94-b54805025a01

	column FileSystemObjectType
		dataType: string
		lineageTag: c0efabc0-d611-408d-b067-0bb421aab99c
		summarizeBy: none
		sourceColumn: FileSystemObjectType

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: string
		lineageTag: 5aea5dc5-3c3f-448b-9cf5-1ffd6eda4b99
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column ServerRedirectedEmbedUri
		dataType: string
		lineageTag: 84d16a4a-1067-45d2-9067-cd7d454c9d88
		summarizeBy: none
		sourceColumn: ServerRedirectedEmbedUri

		annotation SummarizationSetBy = Automatic

	column ServerRedirectedEmbedUrl
		dataType: string
		lineageTag: d8c65ce8-ccbe-4d75-abbf-101bdf79f184
		summarizeBy: none
		sourceColumn: ServerRedirectedEmbedUrl

		annotation SummarizationSetBy = Automatic

	column ContentTypeId
		dataType: string
		lineageTag: bce8c9c6-939a-49f5-9f0f-f7d5f94bcde2
		summarizeBy: none
		sourceColumn: ContentTypeId

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: ac88f12d-555f-4fa4-9bef-fd0de4c4c714
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column OData__ColorTag
		dataType: string
		lineageTag: b1e2c32c-ca14-4cc7-b338-6345f39ffa24
		summarizeBy: none
		sourceColumn: OData__ColorTag

		annotation SummarizationSetBy = Automatic

	column ComplianceAssetId
		dataType: string
		lineageTag: dd638043-058f-4366-8996-777d6b2ed676
		summarizeBy: none
		sourceColumn: ComplianceAssetId

		annotation SummarizationSetBy = Automatic

	column DefectQuantity
		dataType: int64
		formatString: 0
		lineageTag: 10720d8e-5dbf-4d10-8c57-ff7f5d027b35
		summarizeBy: sum
		sourceColumn: DefectQuantity

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column DefectDisposition
		dataType: string
		lineageTag: e216851c-ca09-44f9-8436-f856398597e8
		summarizeBy: none
		sourceColumn: DefectDisposition

		annotation SummarizationSetBy = Automatic

	column DefectType
		dataType: string
		lineageTag: f5449fa0-6b83-442d-8b7d-a3c9336d79cd
		summarizeBy: none
		sourceColumn: DefectType

		annotation SummarizationSetBy = Automatic

	column DefectDescription
		dataType: string
		lineageTag: fbda7ce3-1efa-4307-bf61-7d2bd082f65d
		summarizeBy: none
		sourceColumn: DefectDescription

		annotation SummarizationSetBy = Automatic

	column ImageDefect
		dataType: string
		lineageTag: 86a92fed-6529-4054-ad5a-eb0a45f8eb66
		summarizeBy: none
		sourceColumn: ImageDefect

		annotation SummarizationSetBy = Automatic

	column 'ID.1'
		dataType: string
		lineageTag: c8041c8f-ec23-4701-b1fa-ca7766f7532c
		summarizeBy: none
		sourceColumn: ID.1

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: string
		lineageTag: 519c3904-ace9-43d8-ba49-0887017f250c
		summarizeBy: none
		sourceColumn: Modified

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: string
		lineageTag: 6541c56f-67f5-43bb-94a2-790e1fed286c
		summarizeBy: none
		sourceColumn: Created

		annotation SummarizationSetBy = Automatic

	column AuthorId
		dataType: string
		lineageTag: 572e373d-0ff8-49e0-a6dc-3752c3986eed
		summarizeBy: none
		sourceColumn: AuthorId

		annotation SummarizationSetBy = Automatic

	column EditorId
		dataType: string
		lineageTag: 13196214-db62-4104-aea1-5678fc044cd0
		summarizeBy: none
		sourceColumn: EditorId

		annotation SummarizationSetBy = Automatic

	column OData__UIVersionString
		dataType: string
		lineageTag: 598a3490-628a-43d2-b4e1-f677d52d48a5
		summarizeBy: none
		sourceColumn: OData__UIVersionString

		annotation SummarizationSetBy = Automatic

	column Attachments
		dataType: string
		lineageTag: 1b8b992d-40ad-4659-bd44-fcb7f8c3c226
		summarizeBy: none
		sourceColumn: Attachments

		annotation SummarizationSetBy = Automatic

	column GUID
		dataType: string
		lineageTag: f720da96-c407-4e97-9953-ea896fb516bc
		summarizeBy: none
		sourceColumn: GUID

		annotation SummarizationSetBy = Automatic

	column 'AttachmentFiles.FileName'
		dataType: string
		lineageTag: 1311cc93-50d0-4d93-af7a-904130bb9607
		summarizeBy: none
		sourceColumn: AttachmentFiles.FileName

		annotation SummarizationSetBy = Automatic

	column 'AttachmentFiles.FileNameAsPath'
		dataType: string
		lineageTag: 69b830d0-3888-4447-a5b4-d21ab8a8b253
		summarizeBy: none
		sourceColumn: AttachmentFiles.FileNameAsPath

		annotation SummarizationSetBy = Automatic

	column 'AttachmentFiles.ServerRelativePath'
		dataType: string
		lineageTag: 6208462d-da5a-4440-8ce3-fd4607564348
		summarizeBy: none
		sourceColumn: AttachmentFiles.ServerRelativePath

		annotation SummarizationSetBy = Automatic

	column 'AttachmentFiles.ServerRelativeUrl'
		dataType: string
		lineageTag: edbccc24-5133-41df-8a0c-80ce6f7e259e
		summarizeBy: none
		sourceColumn: AttachmentFiles.ServerRelativeUrl

		annotation SummarizationSetBy = Automatic

	column 'Image URL'
		dataType: string
		lineageTag: 2e448a79-4bff-4fb5-860a-8f0a40c83dcb
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Image URL

		annotation SummarizationSetBy = Automatic

	partition 'Savannah - Container-Defects' = m
		mode: import
		source =
				let
				    Source = SharePoint.Tables("https://keteronline.sharepoint.com/sites/QAContainer/", [ApiVersion = 15]),
				    #"573fee5f-cab0-4dcf-8d45-b7d1189ab69b" = Source{[Id="573fee5f-cab0-4dcf-8d45-b7d1189ab69b"]}[Items],
				    #"Renamed Columns" = Table.RenameColumns(#"573fee5f-cab0-4dcf-8d45-b7d1189ab69b",{{"ID", "ID.1"}}),
				    #"Expanded AttachmentFiles" = Table.ExpandTableColumn(#"Renamed Columns", "AttachmentFiles", {"FileName", "FileNameAsPath", "ServerRelativePath", "ServerRelativeUrl"}, {"AttachmentFiles.FileName", "AttachmentFiles.FileNameAsPath", "AttachmentFiles.ServerRelativePath", "AttachmentFiles.ServerRelativeUrl"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded AttachmentFiles", "Image URL", each "https://keteronline.sharepoint.com" & [AttachmentFiles.ServerRelativeUrl])
				in
				    #"Added Custom"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

