table 'Site Pages'
	lineageTag: 8c284466-f39b-4723-bc41-95988d0e1a68

	column FileSystemObjectType
		dataType: string
		lineageTag: ccc94941-d8f8-442c-bf0b-c506a42a12e7
		summarizeBy: none
		sourceColumn: FileSystemObjectType

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: string
		lineageTag: 2332650f-4936-4021-bf1a-f2d5b44bedba
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column ServerRedirectedEmbedUri
		dataType: string
		lineageTag: 0184d251-4ef9-4769-93b7-bd57380f93b2
		summarizeBy: none
		sourceColumn: ServerRedirectedEmbedUri

		annotation SummarizationSetBy = Automatic

	column ServerRedirectedEmbedUrl
		dataType: string
		lineageTag: 05e33aba-4ad1-491f-9ee2-86a8fcde2bc0
		summarizeBy: none
		sourceColumn: ServerRedirectedEmbedUrl

		annotation SummarizationSetBy = Automatic

	column ContentTypeId
		dataType: string
		lineageTag: 04fd3ab8-91ce-47cc-ae51-c59f7d2944ab
		summarizeBy: none
		sourceColumn: ContentTypeId

		annotation SummarizationSetBy = Automatic

	column OData__ColorTag
		dataType: string
		lineageTag: e8f230c8-f9a7-465e-b4d6-cfee405df6f7
		summarizeBy: none
		sourceColumn: OData__ColorTag

		annotation SummarizationSetBy = Automatic

	column ComplianceAssetId
		dataType: string
		lineageTag: e6361c65-44d7-4953-942c-f094857bf5d7
		summarizeBy: none
		sourceColumn: ComplianceAssetId

		annotation SummarizationSetBy = Automatic

	column WikiField
		dataType: string
		lineageTag: 65ce8e84-a6f7-4dd4-987a-725ab57b0d79
		summarizeBy: none
		sourceColumn: WikiField

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 4110b669-992c-41ec-9c46-8e51592ada76
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column CanvasContent1
		dataType: string
		lineageTag: aca0f4d5-62e6-405c-bc88-9c8b47895b28
		summarizeBy: none
		sourceColumn: CanvasContent1

		annotation SummarizationSetBy = Automatic

	column BannerImageUrl
		dataType: string
		lineageTag: b4f93278-78b2-4ee3-bb88-6142f2112040
		summarizeBy: none
		sourceColumn: BannerImageUrl

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: d765482d-2b9e-4a90-be88-4c7b6736d881
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column PromotedState
		dataType: string
		lineageTag: 7120207e-d463-4efb-b758-6949a14fc0b3
		summarizeBy: none
		sourceColumn: PromotedState

		annotation SummarizationSetBy = Automatic

	column FirstPublishedDate
		dataType: string
		lineageTag: 60927975-2150-4aa7-823a-801632e9b4d9
		summarizeBy: none
		sourceColumn: FirstPublishedDate

		annotation SummarizationSetBy = Automatic

	column LayoutWebpartsContent
		dataType: string
		lineageTag: 38f55e6b-a6ca-4335-a2cf-7ee7d1f69540
		summarizeBy: none
		sourceColumn: LayoutWebpartsContent

		annotation SummarizationSetBy = Automatic

	column OData__AuthorBylineId
		dataType: string
		lineageTag: 1c7b8a10-2d4a-498b-9800-0b59758ac7d5
		summarizeBy: none
		sourceColumn: OData__AuthorBylineId

		annotation SummarizationSetBy = Automatic

	column _AuthorBylineStringId
		dataType: string
		lineageTag: 01494968-25d4-4708-aa59-5b125572d193
		summarizeBy: none
		sourceColumn: _AuthorBylineStringId

		annotation SummarizationSetBy = Automatic

	column OData__TopicHeader
		dataType: string
		lineageTag: 16b1ebb2-15fb-4257-ba8e-97bc19315678
		summarizeBy: none
		sourceColumn: OData__TopicHeader

		annotation SummarizationSetBy = Automatic

	column OData__SPSitePageFlags
		dataType: string
		lineageTag: 80e3675d-17d9-4a55-bc1f-8abe6e40f8d5
		summarizeBy: none
		sourceColumn: OData__SPSitePageFlags

		annotation SummarizationSetBy = Automatic

	column OData__SPCallToAction
		dataType: string
		lineageTag: 0aec6277-6fcd-48ac-88a2-46b0340fdcf5
		summarizeBy: none
		sourceColumn: OData__SPCallToAction

		annotation SummarizationSetBy = Automatic

	column OData__OriginalSourceUrl
		dataType: string
		lineageTag: 5ac267a9-4517-43f0-a536-b35dae031cc4
		summarizeBy: none
		sourceColumn: OData__OriginalSourceUrl

		annotation SummarizationSetBy = Automatic

	column OData__OriginalSourceSiteId
		dataType: string
		lineageTag: 9070c82c-5b94-430d-9775-babcbae2e42f
		summarizeBy: none
		sourceColumn: OData__OriginalSourceSiteId

		annotation SummarizationSetBy = Automatic

	column OData__OriginalSourceWebId
		dataType: string
		lineageTag: 66f02415-4a3a-47b2-9a23-358b5504ea52
		summarizeBy: none
		sourceColumn: OData__OriginalSourceWebId

		annotation SummarizationSetBy = Automatic

	column OData__OriginalSourceListId
		dataType: string
		lineageTag: f4e39724-25be-43ee-9a40-b2159f9acf8f
		summarizeBy: none
		sourceColumn: OData__OriginalSourceListId

		annotation SummarizationSetBy = Automatic

	column OData__OriginalSourceItemId
		dataType: string
		lineageTag: 125076dd-4845-4f60-8395-beced0e27145
		summarizeBy: none
		sourceColumn: OData__OriginalSourceItemId

		annotation SummarizationSetBy = Automatic

	column _SPHideListEditorMetadataStringId
		dataType: string
		lineageTag: 0d7f2d76-0bed-4dd9-8bc8-c084bda598e6
		summarizeBy: none
		sourceColumn: _SPHideListEditorMetadataStringId

		annotation SummarizationSetBy = Automatic

	column 'ID.1'
		dataType: string
		lineageTag: 05051a33-f585-4a4d-8f49-90c08c957858
		summarizeBy: none
		sourceColumn: ID.1

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: string
		lineageTag: 5b4b5568-49aa-4570-b53c-d608305ee2db
		summarizeBy: none
		sourceColumn: Created

		annotation SummarizationSetBy = Automatic

	column AuthorId
		dataType: string
		lineageTag: 7a131f78-05c8-4bcc-83b5-627124542aeb
		summarizeBy: none
		sourceColumn: AuthorId

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: string
		lineageTag: 7a160fbe-5345-4f1e-bba6-b76eed7cda7a
		summarizeBy: none
		sourceColumn: Modified

		annotation SummarizationSetBy = Automatic

	column EditorId
		dataType: string
		lineageTag: d65add1a-d108-49ff-9c68-c0cf99298b69
		summarizeBy: none
		sourceColumn: EditorId

		annotation SummarizationSetBy = Automatic

	column OData__CopySource
		dataType: string
		lineageTag: 834d6c73-629e-49fc-bcc4-632088b8e781
		summarizeBy: none
		sourceColumn: OData__CopySource

		annotation SummarizationSetBy = Automatic

	column CheckoutUserId
		dataType: string
		lineageTag: dac32c20-c732-41a8-93cd-a818f48fc90c
		summarizeBy: none
		sourceColumn: CheckoutUserId

		annotation SummarizationSetBy = Automatic

	column OData__UIVersionString
		dataType: string
		lineageTag: 064b06f2-f0d4-43f8-b3b0-646af7e6e3f8
		summarizeBy: none
		sourceColumn: OData__UIVersionString

		annotation SummarizationSetBy = Automatic

	column GUID
		dataType: string
		lineageTag: 9c89564f-ebc8-46b6-b7b2-bbac8278200f
		summarizeBy: none
		sourceColumn: GUID

		annotation SummarizationSetBy = Automatic

	partition 'Site Pages' = m
		mode: import
		source =
				let
				    Source = SharePoint.Tables("https://keteronline.sharepoint.com/sites/QAContainer/", [ApiVersion = 15]),
				    #"3770e891-cee2-4505-845c-d64d9d7edbcf" = Source{[Id="3770e891-cee2-4505-845c-d64d9d7edbcf"]}[Items],
				    #"Renamed Columns" = Table.RenameColumns(#"3770e891-cee2-4505-845c-d64d9d7edbcf",{{"ID", "ID.1"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

