-- Fabric notebook source

-- METADATA ********************

-- META {
-- META   "kernel_info": {
-- META     "name": "synapse_pyspark"
-- META   },
-- META   "dependencies": {
-- META     "lakehouse": {
-- META       "default_lakehouse": "624ea251-e87f-45d7-8358-a55b3fa46385",
-- META       "default_lakehouse_name": "NA_Supply_Chain",
-- META       "default_lakehouse_workspace_id": "8e2b746d-3224-4a82-8467-a2800eef337e",
-- META       "known_lakehouses": [
-- META         {
-- META           "id": "624ea251-e87f-45d7-8358-a55b3fa46385"
-- META         },
-- META         {
-- META           "id": "be5e5c20-9808-4724-9f8d-cc5502142d75"
-- META         }
-- META       ]
-- META     }
-- META   }
-- META }

-- CELL ********************

-- MAGIC %%sql
-- MAGIC -- CJ - 06-12-2026.1: add distance; base original shipping point on distance to final zip
-- MAGIC -- CJ - 06-12-2026.1: update total storage cost per unit calculation and use 30 DOS; remove previous calculation (including 90 day storage)
-- MAGIC -- CJ - 06-08-2026.1: add daily storage rates & 90 day storage
-- MAGIC -- CJ - 05-28-2026.1: don't include IB costs in net fulfillment fees (include in total at the end)
-- MAGIC -- CJ - 05-26-2026.1: Additional product requirements for WFS

-- METADATA ********************

-- META {
-- META   "language": "sparksql",
-- META   "language_group": "synapse_pyspark",
-- META   "frozen": true,
-- META   "editable": false
-- META }

-- CELL ********************

-- MAGIC %%sql
-- MAGIC CREATE OR REPLACE TABLE fact_walmart_dtc_rates
-- MAGIC USING DELTA
-- MAGIC AS
-- MAGIC  
-- MAGIC WITH 
-- MAGIC sku AS (
-- MAGIC     SELECT
-- MAGIC         CAST(P.Material AS STRING) AS material,
-- MAGIC         P.`Specs.Carton - Volume`  AS carton_volume_ft3,  
-- MAGIC         P.`Specs.Carton - Length`  AS carton_len,  
-- MAGIC         P.`Specs.Carton - Width`   AS carton_width,  
-- MAGIC         P.`Specs.Carton - Height`  AS carton_height,
-- MAGIC 
-- MAGIC         GREATEST( P.`Specs.Carton - Length`, P.`Specs.Carton - Width`, P.`Specs.Carton - Height` ) AS max_dim,
-- MAGIC         LEAST   ( P.`Specs.Carton - Length`, P.`Specs.Carton - Width`, P.`Specs.Carton - Height` ) AS small_dim,
-- MAGIC         ROUND   (
-- MAGIC             (P.`Specs.Carton - Length` + P.`Specs.Carton - Width` + P.`Specs.Carton - Height`)
-- MAGIC                 - GREATEST( P.`Specs.Carton - Length`, P.`Specs.Carton - Width`, P.`Specs.Carton - Height` )
-- MAGIC                 - LEAST   ( P.`Specs.Carton - Length`, P.`Specs.Carton - Width`, P.`Specs.Carton - Height` ) ,
-- MAGIC             2
-- MAGIC         ) AS med_dim,
-- MAGIC 
-- MAGIC         P.`Specs.Carton - Weight`  AS carton_weight_lb,
-- MAGIC         P.`Specs.Carton - Weight` * 16 AS carton_weight_oz,
-- MAGIC 
-- MAGIC         (P.`Specs.Carton - Length` * P.`Specs.Carton - Width` * P.`Specs.Carton - Height`) / 139 AS dim_weight_lbs,
-- MAGIC         ((P.`Specs.Carton - Length` * P.`Specs.Carton - Width` * P.`Specs.Carton - Height`) / 139) * 16 AS dim_weight_oz,
-- MAGIC 
-- MAGIC         CASE
-- MAGIC             WHEN P.`Specs.Carton - Weight` < 1 THEN CEIL(P.`Specs.Carton - Weight` + 0.25)
-- MAGIC             ELSE GREATEST(
-- MAGIC                 CEIL(P.`Specs.Carton - Weight` + 0.25),
-- MAGIC                 CEIL(((P.`Specs.Carton - Length` * P.`Specs.Carton - Width` * P.`Specs.Carton - Height`) / 139) + 0.25)
-- MAGIC             )
-- MAGIC         END AS shipping_weight_lbs,
-- MAGIC 
-- MAGIC         CASE
-- MAGIC             WHEN P.`Specs.Carton - Weight` < 1 THEN CEIL((P.`Specs.Carton - Weight` + 0.25) * 16)
-- MAGIC             ELSE GREATEST(
-- MAGIC                 CEIL((P.`Specs.Carton - Weight` + 0.25) * 16),
-- MAGIC                 CEIL( ( ((P.`Specs.Carton - Length` * P.`Specs.Carton - Width` * P.`Specs.Carton - Height`) / 139) + 0.25 ) * 16)
-- MAGIC             )
-- MAGIC         END AS shipping_weight_oz,
-- MAGIC 
-- MAGIC         P.`Length & Girth`                                  AS length_girth,
-- MAGIC         P.`Cont_Qty`                                        AS cont_qty,
-- MAGIC         P.`TL Qty`                                          AS tl_qty,
-- MAGIC         P.LTL_Parcel                                        AS ltl_parcel,
-- MAGIC         case when P.LTL_Parcel = 'Parcel' then '07' else '06' end AS shipping_point_type,
-- MAGIC         Z.COGS                                              AS cogs,
-- MAGIC         P.`Model`                                           AS model,
-- MAGIC         P.`SS/PLT_Qty`                                      AS ss_plt_qty,
-- MAGIC         P.`Stacked_Cont/TL`                                 AS stacked_cont_tl,
-- MAGIC         IF(UPPER(`Stacked_Cont/TL`) LIKE ('%P%'), 1, 0)     AS pallet_present,
-- MAGIC 
-- MAGIC         P.`PC Business Unit`                                AS pc_business_unit
-- MAGIC 
-- MAGIC     FROM `DIM Product` P
-- MAGIC     LEFT JOIN (
-- MAGIC         WITH cte AS (
-- MAGIC             SELECT *,
-- MAGIC                 ROW_NUMBER() OVER (PARTITION BY Material ORDER BY Plnt) AS rn
-- MAGIC             FROM `dbo`.`DIM ZMM02 COGS`
-- MAGIC             WHERE Plnt IN ('67', '73')
-- MAGIC         )
-- MAGIC         SELECT
-- MAGIC             Material,
-- MAGIC             `Standard price`/per AS COGS
-- MAGIC         FROM cte
-- MAGIC         WHERE rn = 1
-- MAGIC     ) Z ON P.Material = Z.Material
-- MAGIC     -- WHERE ltl_parcel IN ('Parcel')
-- MAGIC ),
-- MAGIC 
-- MAGIC sku_category as (
-- MAGIC     SELECT *,
-- MAGIC         CASE 
-- MAGIC             WHEN 
-- MAGIC                 shipping_weight_lbs <= 150 AND
-- MAGIC                     max_dim <= 108 AND
-- MAGIC                     length_girth <= 165 AND 
-- MAGIC                     -- CJ - 05-26-2026.1
-- MAGIC                     med_dim <= 105 AND -- median side is <= 105"
-- MAGIC                     small_dim <= 93 -- smallest side is <= 93"
-- MAGIC                 THEN TRUE 
-- MAGIC             ELSE FALSE 
-- MAGIC         END AS multichannel_eligible_flag,
-- MAGIC 
-- MAGIC         CASE
-- MAGIC             WHEN shipping_weight_lbs < 33 AND max_dim < 30 AND med_dim < 18 AND small_dim < 18 THEN TRUE
-- MAGIC             ELSE FALSE
-- MAGIC         END AS sortable_flag,
-- MAGIC 
-- MAGIC         CASE
-- MAGIC             WHEN shipping_weight_lbs < 33 AND max_dim < 30 AND med_dim < 18 AND small_dim < 18 THEN (2.75 * carton_volume_ft3)
-- MAGIC             ELSE 2.25 * carton_volume_ft3
-- MAGIC         END AS ITS_fee,
-- MAGIC 
-- MAGIC         CASE
-- MAGIC             WHEN max_dim > 48 OR med_dim > 30 OR length_girth > 105 THEN TRUE
-- MAGIC             ELSE FALSE
-- MAGIC         END AS oversize_flag,
-- MAGIC 
-- MAGIC         CASE 
-- MAGIC             WHEN 
-- MAGIC                 (max_dim > 48 AND max_dim <= 96) OR
-- MAGIC                 (med_dim > 30) OR
-- MAGIC                 (length_girth > 105 AND length_girth <= 130)
-- MAGIC                 THEN 3.0
-- MAGIC             WHEN 
-- MAGIC                 (max_dim > 96 AND max_dim <= 108) OR
-- MAGIC                 (length_girth > 130 AND length_girth <= 165)
-- MAGIC                 THEN 20.0
-- MAGIC             ELSE 0.0
-- MAGIC         END AS oversize_fee,
-- MAGIC 
-- MAGIC         CASE
-- MAGIC             WHEN shipping_weight_oz <= 6 THEN 7.45
-- MAGIC             WHEN shipping_weight_oz > 6 AND shipping_weight_oz <= 12 THEN 7.75
-- MAGIC             WHEN shipping_weight_oz > 12 AND shipping_weight_lbs <= 1 THEN 8.05
-- MAGIC             WHEN shipping_weight_lbs > 1 AND shipping_weight_lbs <= 30 THEN 8.65 + GREATEST(0, shipping_weight_lbs-2) * 0.6
-- MAGIC             WHEN shipping_weight_lbs > 30 AND shipping_weight_lbs <= 150 THEN 28.05 + GREATEST(0, shipping_weight_lbs-31) * 0.6
-- MAGIC         END AS fulfillment_fees,
-- MAGIC 
-- MAGIC         -- CJ - 06-08-2026.1
-- MAGIC         (0.75 / (365/12) ) * carton_volume_ft3 as daily_storage_0_30,
-- MAGIC         ( (0.75 * (9/12) + 1.5 * (3/12) ) / (365/12) ) * carton_volume_ft3 as daily_storage_31_365,
-- MAGIC         (2.25 / (365/12) ) * carton_volume_ft3 as daily_storage_366_450,
-- MAGIC         (7.50 / (365/12) ) * carton_volume_ft3 as daily_storage_450_plus
-- MAGIC 
-- MAGIC     FROM sku
-- MAGIC )
-- MAGIC 
-- MAGIC -- CJ - 06-12-2026.1 BEGIN
-- MAGIC ,storage_base as (
-- MAGIC     select
-- MAGIC         a.Material,
-- MAGIC         b.carton_volume_ft3,
-- MAGIC         sum(-a.`Combined Qty`) as fc_sales_units
-- MAGIC     from `FACT Component Forecast Initial` a
-- MAGIC     left join sku_category b on a.Material = b.material
-- MAGIC     join (
-- MAGIC         select distinct Material
-- MAGIC         from `DIM Account` a
-- MAGIC         join `DIM Customer` b 
-- MAGIC             on a.Payer = b.`Payer Key`
-- MAGIC         where b.ECOM is not null
-- MAGIC     ) c on a.Material = c.Material
-- MAGIC     where (a.`SOW` between a.`Today SOW` and (a.`Today SOW` + 139))
-- MAGIC         and b.multichannel_eligible_flag
-- MAGIC     group by a.Material, b.carton_volume_ft3
-- MAGIC )
-- MAGIC 
-- MAGIC ,storage_calc as (
-- MAGIC     select
-- MAGIC         *,
-- MAGIC         140 as fc_sales_days,
-- MAGIC         30 as avg_DOS,
-- MAGIC 
-- MAGIC         -- core drivers
-- MAGIC         fc_sales_units / 140.0 as fc_ADS,
-- MAGIC         30 * (fc_sales_units / 140.0) as avg_inventory
-- MAGIC     from storage_base
-- MAGIC )
-- MAGIC 
-- MAGIC ,storage_rate_per_day as (
-- MAGIC     select
-- MAGIC         *,
-- MAGIC         (0.75 / (365/12) ) * carton_volume_ft3 as daily_storage_0_30
-- MAGIC         -- ( (0.75 * (9/12) + 1.5 * (3/12) ) / (365/12) ) * carton_volume_ft3 as daily_storage_31_365,
-- MAGIC         -- (2.25 / (365/12) ) * carton_volume_ft3 as daily_storage_366_450,
-- MAGIC         -- (7.50 / (365/12) ) * carton_volume_ft3 as daily_storage_450_plus
-- MAGIC 
-- MAGIC     from storage_calc
-- MAGIC )
-- MAGIC 
-- MAGIC ,storage_final as (
-- MAGIC     select
-- MAGIC         Material,
-- MAGIC         carton_volume_ft3,
-- MAGIC         fc_sales_days,
-- MAGIC         avg_DOS,
-- MAGIC 
-- MAGIC         fc_sales_units,
-- MAGIC         fc_ADS,
-- MAGIC         avg_inventory,
-- MAGIC 
-- MAGIC         -- total storage cost
-- MAGIC         0.5 * avg_DOS * avg_inventory * daily_storage_0_30 as total_storage_cost, -- *will need to update if we ever go beyond 30 DOS
-- MAGIC         -- per unit cost
-- MAGIC         0.5 * avg_DOS * daily_storage_0_30 as total_storage_cost_per_unit
-- MAGIC 
-- MAGIC     from storage_rate_per_day
-- MAGIC )
-- MAGIC -- CJ - 06-12-2026.1 END
-- MAGIC ,zip as (
-- MAGIC     SELECT a.*
-- MAGIC         -- CJ - 06-12-2026.1
-- MAGIC         -- ,(daily_storage_0_30 * 30) + (daily_storage_31_365 * 60) as `90_day_storage_rate` -- CJ - 06-08-2026.1; 
-- MAGIC         ,t.fc_sales_days
-- MAGIC         ,t.avg_DOS
-- MAGIC         ,t.fc_sales_units
-- MAGIC         ,t.fc_ADS
-- MAGIC         ,t.avg_inventory
-- MAGIC         ,t.total_storage_cost
-- MAGIC         ,t.total_storage_cost_per_unit
-- MAGIC         
-- MAGIC         -- CJ - 06-12-2026.1
-- MAGIC         ,case when b.`Distance from DHL` <= b.`Distance from Rancho` then '4674' else '367G' end as shipping_point
-- MAGIC         ,case when b.`Distance from DHL` <= b.`Distance from Rancho` then `Distance from DHL` else `Distance from Rancho` end as distance
-- MAGIC         -- ,c.shipping_point
-- MAGIC 
-- MAGIC         ,c.IB_TL_Cost
-- MAGIC         ,c.IB_TL_Cost/a.tl_qty as IB_ea_cost
-- MAGIC         -- ,coalesce(c.IB_TL_Cost/a.tl_qty,0) + -- CJ - 05-28-2026.1
-- MAGIC             ,coalesce(ITS_fee, 0) + coalesce(oversize_fee, 0) + coalesce(fulfillment_fees, 0) as net_fulfillment_cost
-- MAGIC         ,b.POSTAL_CODE as destination_zip
-- MAGIC         ,b.`Postal Code Clean` as dest_zip_clean
-- MAGIC         ,b.REGION as state
-- MAGIC         ,b.`City List` as city
-- MAGIC         ,b.`DAT US Region` as dat_region
-- MAGIC     FROM sku_category a
-- MAGIC     -- CJ - 06-12-2026.1
-- MAGIC     LEFT JOIN storage_final t on a.material = t.Material
-- MAGIC     cross join `DIM USA CA Zips` b
-- MAGIC     left join (
-- MAGIC         -- with base as (
-- MAGIC         --     select
-- MAGIC         --         a.`DAT US Region` as DAT_Region
-- MAGIC         --         ,avg(a.`DHL TL Cost`) as DHL_TL_Cost
-- MAGIC         --         ,avg(a.`Rancho TL Cost`) as Rancho_TL_Cost
-- MAGIC         --     from `DIM USA CA Zips` a
-- MAGIC         --     group by 1
-- MAGIC         -- )
-- MAGIC 
-- MAGIC         -- select 
-- MAGIC         --     a.DAT_Region
-- MAGIC         --     ,case when a.DHL_TL_Cost <= a.Rancho_TL_Cost then '4674' else '367G' end as shipping_point
-- MAGIC         --     ,case when a.DHL_TL_Cost <= a.Rancho_TL_Cost then a.DHL_TL_Cost else a.Rancho_TL_Cost end as IB_TL_Cost
-- MAGIC         -- from base a
-- MAGIC 
-- MAGIC         -- CJ - 06-12-2026.1
-- MAGIC         SELECT
-- MAGIC             a.`DAT US Region` AS DAT_Region,
-- MAGIC             AVG(
-- MAGIC                 CASE
-- MAGIC                     WHEN a.`Distance from DHL` <= a.`Distance from Rancho`
-- MAGIC                         THEN a.`DHL TL Cost`
-- MAGIC                     ELSE a.`Rancho TL Cost`
-- MAGIC                 END
-- MAGIC             ) AS IB_TL_Cost
-- MAGIC         FROM `DIM USA CA Zips` a
-- MAGIC         GROUP BY a.`DAT US Region`
-- MAGIC     ) c on b.`DAT US Region` = c.DAT_Region
-- MAGIC 
-- MAGIC     WHERE true
-- MAGIC         and a.multichannel_eligible_flag
-- MAGIC         and b.`Postal Code Country` = 'USA'
-- MAGIC )
-- MAGIC 
-- MAGIC select 
-- MAGIC     a.material
-- MAGIC     ,a.carton_volume_ft3
-- MAGIC     -- ,a.carton_len
-- MAGIC     -- ,a.carton_width
-- MAGIC     -- ,a.carton_height
-- MAGIC     ,a.max_dim
-- MAGIC     ,a.small_dim
-- MAGIC     ,a.med_dim
-- MAGIC     ,a.carton_weight_lb
-- MAGIC     ,a.carton_weight_oz
-- MAGIC     ,a.dim_weight_lbs
-- MAGIC     ,a.dim_weight_oz
-- MAGIC     ,a.shipping_weight_lbs
-- MAGIC     ,a.shipping_weight_oz
-- MAGIC     ,a.length_girth
-- MAGIC     ,a.cont_qty
-- MAGIC     ,a.tl_qty
-- MAGIC     ,a.ltl_parcel
-- MAGIC     ,a.cogs
-- MAGIC     ,a.model
-- MAGIC     ,a.ss_plt_qty
-- MAGIC     ,a.stacked_cont_tl
-- MAGIC     ,a.pallet_present
-- MAGIC     ,a.pc_business_unit
-- MAGIC 
-- MAGIC     ,b.Port
-- MAGIC     ,'699-WMT' as shipping_point
-- MAGIC     ,'Walmart' as shipping_point_desc
-- MAGIC     ,b.shipping_point_type
-- MAGIC     ,b.shipping_point_type_desc
-- MAGIC     ,b.shipping_point_zip
-- MAGIC     ,b.YR50
-- MAGIC     ,b.YR73
-- MAGIC     ,b.YR51
-- MAGIC     ,b.YR53
-- MAGIC     ,CASE
-- MAGIC         WHEN a.shipping_point = '4674' THEN 
-- MAGIC             CASE
-- MAGIC                 WHEN a.pc_business_unit = 'GF NA' THEN 181.21
-- MAGIC                 WHEN a.pc_business_unit = 'Tools' THEN 108.21
-- MAGIC                 WHEN a.pc_business_unit = 'F & P EU' THEN 75.99
-- MAGIC                 WHEN a.pc_business_unit = 'Cabinets & Shelving EU' THEN 74.62
-- MAGIC                 WHEN a.pc_business_unit = 'Sheds & Buildings' THEN 68.97
-- MAGIC                 WHEN a.pc_business_unit = 'Deck Boxes' THEN 87.41
-- MAGIC                 WHEN a.pc_business_unit = 'Packout' THEN 117.22
-- MAGIC                 WHEN a.pc_business_unit IN ('Lifestyle', 'Leisure', 'Deck Boxes & Leisure')  THEN 86.89
-- MAGIC                 ELSE NULL
-- MAGIC             END
-- MAGIC         WHEN a.shipping_point = '367G' THEN
-- MAGIC             450.0 + --ContainerReceipt
-- MAGIC             2.50 + --Order Processing
-- MAGIC             CASE
-- MAGIC                 WHEN a.ltl_parcel = 'LTL' THEN 
-- MAGIC                     6.75 + --handling/picking of sheds
-- MAGIC                     6.50 -- strapping
-- MAGIC                 ELSE
-- MAGIC                     0.75 --handling/picking for parcel
-- MAGIC             END
-- MAGIC         ELSE NULL
-- MAGIC     END AS YR60
-- MAGIC 
-- MAGIC     ,b.YR50/a.cont_qty as YR50_ea_cost
-- MAGIC     ,b.YR73/a.cont_qty as YR73_ea_cost
-- MAGIC     ,b.YR51/a.cont_qty as YR51_ea_cost
-- MAGIC     ,b.YR53/a.cont_qty as YR53_ea_cost
-- MAGIC     ,CASE
-- MAGIC         WHEN a.shipping_point = '4674' THEN
-- MAGIC             CASE
-- MAGIC                 WHEN a.pc_business_unit = 'GF NA' THEN 181.21/nullif(a.ss_plt_qty, 0)
-- MAGIC                 WHEN a.pc_business_unit = 'Tools' THEN 108.21/nullif(a.ss_plt_qty, 0)
-- MAGIC                 WHEN a.pc_business_unit = 'F & P EU' THEN 75.99/nullif(a.ss_plt_qty, 0)
-- MAGIC                 WHEN a.pc_business_unit = 'Cabinets & Shelving EU' THEN 74.62/nullif(a.ss_plt_qty, 0)
-- MAGIC                 WHEN a.pc_business_unit = 'Sheds & Buildings' THEN 68.97/nullif(a.ss_plt_qty, 0)
-- MAGIC                 WHEN a.pc_business_unit = 'Deck Boxes' THEN 87.41/nullif(a.ss_plt_qty, 0)
-- MAGIC                 WHEN a.pc_business_unit = 'Packout' THEN 117.22/nullif(a.ss_plt_qty, 0)
-- MAGIC                 WHEN a.pc_business_unit IN ('Lifestyle', 'Leisure', 'Deck Boxes & Leisure')  THEN 86.89/nullif(a.ss_plt_qty, 0)
-- MAGIC                 ELSE NULL
-- MAGIC             END
-- MAGIC         WHEN shipping_point_key = '367G - 06' THEN
-- MAGIC             450.0/ NULLIF(a.cont_qty, 0) + --ContainerReceipt
-- MAGIC             2.50 + --Order Processing
-- MAGIC             CASE
-- MAGIC                 WHEN a.ltl_parcel = 'LTL' THEN 
-- MAGIC                     6.75 + --handling/picking of sheds
-- MAGIC                     6.50 -- strapping
-- MAGIC                 ELSE
-- MAGIC                     0.75 --handling/picking for parcel
-- MAGIC             END
-- MAGIC         ELSE NULL
-- MAGIC     END AS YR60_ea_cost
-- MAGIC 
-- MAGIC     ,concat('Walmart', ' - ', b.shipping_point_type_desc) as shipping_point_key_desc
-- MAGIC     ,concat('699-WMT', ' - ', b.shipping_point_type ) as shipping_point_key
-- MAGIC 
-- MAGIC     ,a.multichannel_eligible_flag
-- MAGIC     ,a.sortable_flag
-- MAGIC     ,a.ITS_fee
-- MAGIC     ,a.oversize_flag
-- MAGIC     ,a.oversize_fee
-- MAGIC     ,a.fulfillment_fees
-- MAGIC 
-- MAGIC     -- CJ - 06-08-2026.1
-- MAGIC     -- ,a.daily_storage_0_30
-- MAGIC     -- ,a.daily_storage_31_365
-- MAGIC     -- ,a.daily_storage_366_450
-- MAGIC     -- ,a.daily_storage_450_plus
-- MAGIC     -- ,a.`90_day_storage_rate`
-- MAGIC     -- CJ - 06-12-2026.1
-- MAGIC     ,a.fc_sales_days
-- MAGIC     ,a.avg_DOS
-- MAGIC     ,a.fc_sales_units
-- MAGIC     ,a.fc_ADS
-- MAGIC     ,a.avg_inventory
-- MAGIC     ,a.total_storage_cost
-- MAGIC     ,a.total_storage_cost_per_unit
-- MAGIC 
-- MAGIC     ,a.shipping_point as shipping_point_origin
-- MAGIC     ,a.IB_TL_Cost
-- MAGIC     ,a.IB_ea_cost
-- MAGIC     ,a.net_fulfillment_cost
-- MAGIC     ,a.destination_zip
-- MAGIC     ,a.dest_zip_clean
-- MAGIC     ,a.state
-- MAGIC     ,a.city
-- MAGIC     ,a.dat_region
-- MAGIC 
-- MAGIC     -- CJ - 06-12-2026.1
-- MAGIC     ,a.distance
-- MAGIC 
-- MAGIC from zip a
-- MAGIC inner join `DIM DTC Ship Point Key` b
-- MAGIC     on a.shipping_point = b.shipping_point
-- MAGIC     and a.shipping_point_type = b.shipping_point_type 
-- MAGIC -- where true
-- MAGIC --     and material in ('255123')
-- MAGIC --     and destination_zip in ('30305', '90065') 
-- MAGIC -- order by material
-- MAGIC ;

-- METADATA ********************

-- META {
-- META   "language": "sparksql",
-- META   "language_group": "synapse_pyspark"
-- META }
