CREATE TABLE [dbo].[DI YM6P FACT HELP] (

	[Material] varchar(8000) NULL, 
	[MRP Area] varchar(8000) NULL, 
	[Today] date NULL, 
	[Today SOW] date NULL, 
	[Remaining?] varchar(8000) NULL, 
	[Combined Date] date NULL, 
	[Data Source] varchar(8000) NULL, 
	[Combined Qty] bigint NULL, 
	[MRPSKU Key] varchar(8000) NULL, 
	[Plant] bigint NULL, 
	[Storage Location] varchar(8000) NULL, 
	[SOW] date NULL, 
	[PO Number] varchar(8000) NULL, 
	[Purchasing Group] varchar(8000) NULL, 
	[Storage Location Orig] varchar(8000) NULL, 
	[Purchase Order Date] date NULL, 
	[AASalOrd] varchar(8000) NULL, 
	[Supplier] bigint NULL, 
	[Item] varchar(8000) NULL, 
	[Material Description] varchar(8000) NULL, 
	[Order Quantity] bigint NULL, 
	[Net Order Value] float NULL, 
	[Sales document] bigint NULL, 
	[ReqDelivDate] date NULL, 
	[Confirm. Category] varchar(8000) NULL, 
	[ConfirmDelvDate] date NULL, 
	[GR Processing Time] bigint NULL, 
	[LA Date] date NULL, 
	[CalcArravDate] date NULL, 
	[Delivery] bigint NULL, 
	[Billing Document] bigint NULL, 
	[Container] varchar(8000) NULL, 
	[Inb.delivery] bigint NULL, 
	[Entry Port] varchar(8000) NULL, 
	[VesselName] varchar(8000) NULL, 
	[First GR date for item] date NULL, 
	[Deletion Indicator] varchar(8000) NULL, 
	[Ship-to party's purchase order no_] varchar(8000) NULL, 
	[Ship-to party] varchar(8000) NULL, 
	[Ship Date] date NULL, 
	[Days to Port] bigint NULL, 
	[Storage Type] varchar(8000) NULL, 
	[DTP Group] varchar(8000) NULL, 
	[Payer] varchar(8000) NULL, 
	[PO Number.1] varchar(8000) NULL, 
	[Customer SKU] varchar(8000) NULL, 
	[Requested deliv.date] date NULL, 
	[Planned date CheckIn] date NULL, 
	[Planned shipment end] date NULL, 
	[Ship-To Party.1] varchar(8000) NULL, 
	[Planned Delivery Date] date NULL, 
	[Order Status] varchar(8000) NULL, 
	[Early/LateDirectPO] varchar(8000) NULL
);