CREATE TABLE [dbo].[DIM Product] (

	[Material] varchar(8000) NULL, 
	[Model] bigint NULL, 
	[Description] varchar(8000) NULL, 
	[Customer] bigint NULL, 
	[Dept] varchar(8000) NULL, 
	[Customer_1] varchar(8000) NULL, 
	[Vendor #] varchar(8000) NULL, 
	[Carton/Bag_Qty] bigint NULL, 
	[Layer Qty] bigint NULL, 
	[SS/PLT_Qty] bigint NULL, 
	[Cont_Qty] float NULL, 
	[TL Qty] bigint NULL, 
	[Stacked_Cont/TL] varchar(8000) NULL, 
	[Stacked] varchar(8000) NULL, 
	[Brand] varchar(8000) NULL, 
	[Color] varchar(8000) NULL, 
	[Note] varchar(8000) NULL, 
	[Supplier] bigint NULL, 
	[UPC/EAN] bigint NULL, 
	[Carton I2of5] bigint NULL, 
	[Pallet I2of5] bigint NULL, 
	[Private Label] varchar(8000) NULL, 
	[Opened] date NULL, 
	[Plant-sp.matl status] varchar(8000) NULL, 
	[Disco Date] date NULL, 
	[PC Business Unit] varchar(8000) NULL, 
	[HTS Code] varchar(8000) NULL, 
	[MSRP] varchar(8000) NULL, 
	[Document Year] varchar(8000) NULL, 
	[SKU & Desc] varchar(8000) NULL, 
	[Pack Type.Final] varchar(8000) NULL, 
	[Pack Type.General] varchar(8000) NULL, 
	[Port Free Days] float NULL, 
	[DIM BOM Combined.BOM Type] varchar(8000) NULL, 
	[Specs.Carton - Length] float NULL, 
	[Specs.Carton - Width] float NULL, 
	[Specs.Carton - Height] float NULL, 
	[Specs.Carton - Volume] float NULL, 
	[Specs.Carton - Weight] float NULL, 
	[Specs.Carton - cf] float NULL, 
	[Specs.Carton - pcf] float NULL, 
	[Specs.Pallet - Length] float NULL, 
	[Specs.Pallet - Width] float NULL, 
	[Specs.Pallet - Height] float NULL, 
	[Specs.Pallet - Volume] float NULL, 
	[Specs.Pallet - Weight] float NULL, 
	[Specs.Pallet - cf] float NULL, 
	[Specs.Pallet - pcf] float NULL, 
	[Specs.LP] float NULL, 
	[Specs.Carton Class] float NULL, 
	[Specs.SS/PLT Class] float NULL, 
	[Specs.Carton Dim Wt] float NULL, 
	[Specs.Oversize +130" Max 165"] float NULL, 
	[Specs.SAP] varchar(8000) NULL, 
	[Specs.Override] varchar(8000) NULL, 
	[Specs.Linear Ft CTN] float NULL, 
	[Specs.Current] varchar(8000) NULL, 
	[Dim Products.ACT PROD SITE] varchar(8000) NULL, 
	[Dim Products.ACT PROD SITE Region] varchar(8000) NULL, 
	[Dim Products.Brand desc] varchar(8000) NULL, 
	[Dim Products.EAN] varchar(8000) NULL, 
	[Dim Products.Image] varchar(8000) NULL, 
	[Dim Products.ITEM GROUP] varchar(8000) NULL, 
	[Dim Products.MARKET GROUP] varchar(8000) NULL, 
	[Dim Products.OUTDOOR/INDOOR] varchar(8000) NULL, 
	[Dim Products.PRODUCT CATEGORY] varchar(8000) NULL, 
	[Dim Products.PRODUCT LINE DESC] varchar(8000) NULL, 
	[Dim Products.PRODUCT MANAGEMENT/Category] varchar(8000) NULL, 
	[Dim Products.PRODUCT TYPE] varchar(8000) NULL, 
	[Dim Products.ProductOrg] varchar(8000) NULL, 
	[Dim Products.Region] varchar(8000) NULL, 
	[Dim Products.SAP_MATERIALTYPE] varchar(8000) NULL, 
	[Dim Products.SKU Group] varchar(8000) NULL, 
	[Dim Products.SKU Group #] varchar(8000) NULL, 
	[Dim Products.SKU Group # & Desc] varchar(8000) NULL, 
	[Dim Products.SKU Level] varchar(8000) NULL, 
	[Dim Products.SKU Level # & Desc] varchar(8000) NULL, 
	[Dim Products.SubContinent Production] varchar(8000) NULL, 
	[Crossdock] varchar(8000) NULL, 
	[Specs.Carton - Volume - in_] float NULL, 
	[FedEx Ground US Dim Divisor] bigint NULL, 
	[FedEx US Dim Weight] bigint NULL, 
	[Length & Girth] float NULL, 
	[FedEx AHS Dim Flag] bit NULL, 
	[FedEx AHS Dim US Billable Weight] float NULL, 
	[FedEx AHS Weight Flag] bit NULL, 
	[FedEx Oversize Flag] bit NULL, 
	[FedEx Oversize US Billable Weight] float NULL, 
	[FedEx Unauthorized Flag] bit NULL, 
	[FedEx Unauthorized US Billable Weight] float NULL, 
	[FedEx Applied AHS Category] varchar(8000) NULL, 
	[FedEx US Final Billable Weight] float NULL, 
	[Last Sale Date.1] date NULL, 
	[Warranty _Year_] bigint NULL, 
	[Last Warranty Date] date NULL
);