CREATE TABLE [dbo].[FACT YS10N Open] (

	[Material] bigint NULL, 
	[Payer] varchar(8000) NULL, 
	[MRP Area] varchar(8000) NULL, 
	[Today] date NULL, 
	[Today SOW] date NULL, 
	[Remaining?] varchar(8000) NULL, 
	[Combined Date] date NULL, 
	[Data Source] varchar(8000) NULL, 
	[Combined Qty] float NULL, 
	[MRPSKU Key] varchar(8000) NULL, 
	[Sales Organization] bigint NULL, 
	[Plant] varchar(8000) NULL, 
	[Storage Location] varchar(8000) NULL, 
	[SOW] date NULL, 
	[Shipping Point/Receiving Pt] varchar(8000) NULL, 
	[Payer name] varchar(8000) NULL, 
	[Reason for rejection] bigint NULL, 
	[Reason for rejection description] varchar(8000) NULL, 
	[Order reason] varchar(8000) NULL, 
	[Order reason_1] varchar(8000) NULL, 
	[PO Number] varchar(8000) NULL, 
	[Sales Order] varchar(8000) NULL, 
	[Delivery] varchar(8000) NULL, 
	[Shipment Number] varchar(8000) NULL, 
	[Shipping type] varchar(8000) NULL, 
	[Customer SKU] varchar(8000) NULL, 
	[Net value] float NULL, 
	[SO Created Date] date NULL, 
	[Delivery Creation Date] date NULL, 
	[Confirmation Date] date NULL, 
	[Requested deliv.date] date NULL, 
	[Guarantee Date] date NULL, 
	[Original Delivery Date] date NULL, 
	[SO Billing Date] date NULL, 
	[Ship-To Party Region] varchar(8000) NULL, 
	[Planning end] date NULL, 
	[Planned date CheckIn] date NULL, 
	[Planned time CheckIn] datetime2(6) NULL, 
	[Trailer No_] varchar(8000) NULL, 
	[Planned shipment end] date NULL, 
	[Load Delay Reason] varchar(8000) NULL, 
	[Act. Gds Mvmnt Date] date NULL, 
	[Invoice Billing Date] date NULL, 
	[Profit Center] bigint NULL, 
	[Carrier SCAC code] varchar(8000) NULL, 
	[Carrier Name] varchar(8000) NULL, 
	[Carrier Code] varchar(8000) NULL, 
	[Carrier Service] varchar(8000) NULL, 
	[Load No_] varchar(8000) NULL, 
	[Ship-To Zip] varchar(8000) NULL, 
	[Spare Part Indicator] varchar(8000) NULL, 
	[Ship-To Party] varchar(8000) NULL, 
	[Sales Document Item] varchar(8000) NULL, 
	[PayerMRPSKUSOW] varchar(8000) NULL, 
	[Confirm. Category] varchar(8000) NULL, 
	[LA Date] date NULL, 
	[CalcArravDate] date NULL, 
	[Container] varchar(8000) NULL, 
	[Entry Port] varchar(8000) NULL, 
	[VesselName] varchar(8000) NULL, 
	[Ship Date] date NULL, 
	[SalesOrderItem] varchar(8000) NULL
);