CREATE TABLE [dbo].[FACT YS10N Past] (

	[SourceTable] varchar(8000) NULL, 
	[SBU] bigint NULL, 
	[AcquisitionStatus] bigint NULL, 
	[Material] varchar(8000) NULL, 
	[RetailerKey] bigint NULL, 
	[Sales Order] bigint NULL, 
	[FSL_SOLDTO] bigint NULL, 
	[ship_to] bigint NULL, 
	[FSL_SalesOrgKey] bigint NULL, 
	[FSL_ShipPoint_KEY] bigint NULL, 
	[REQUEST_KEY] bigint NULL, 
	[FIRST_DAY_KEY] bigint NULL, 
	[GUARANT_KEY] bigint NULL, 
	[PODAT_KEY] bigint NULL, 
	[GOOD_IS_Key] bigint NULL, 
	[PL_GOOD_IS_KEY] bigint NULL, 
	[VKORG] varchar(8000) NULL, 
	[VBELN] varchar(8000) NULL, 
	[OrderLine] varchar(8000) NULL, 
	[Order with Line Number] varchar(8000) NULL, 
	[Gross Sale] decimal(38,6) NULL, 
	[Plant] varchar(8000) NULL, 
	[Storage Location] varchar(8000) NULL, 
	[Shipping Point/Receiving Pt] varchar(8000) NULL, 
	[ROUTE] varchar(8000) NULL, 
	[First Date] date NULL, 
	[PL_GOOD_IS] varchar(8000) NULL, 
	[Guarantee Date] date NULL, 
	[Requested deliv.date] varchar(8000) NULL, 
	[Combined Qty] float NULL, 
	[end_customer] bigint NULL, 
	[Order Type] varchar(8000) NULL, 
	[VTWEG] varchar(8000) NULL, 
	[GOOD_IS] varchar(8000) NULL, 
	[POSNN] varchar(8000) NULL, 
	[EXPVZ] varchar(8000) NULL, 
	[Route in days] bigint NULL, 
	[Sh_wind] bigint NULL, 
	[Delivery] bigint NULL, 
	[PODAT] varchar(8000) NULL, 
	[plan_good_is_sw] bigint NULL, 
	[QUANTITY ON TIME] decimal(38,6) NULL, 
	[QUANTITY CUT] decimal(38,6) NULL, 
	[On time value] decimal(38,6) NULL, 
	[DateDailyKey] bigint NULL, 
	[Payer] varchar(8000) NULL, 
	[IncotermKey] bigint NULL, 
	[Type_Definition] bigint NULL, 
	[SW] bigint NULL, 
	[ABGRU] varchar(8000) NULL, 
	[GSBER] varchar(8000) NULL, 
	[ABGRU_KEY] bigint NULL, 
	[FSL_PSTYV] varchar(8000) NULL, 
	[ITEM_CAT_Key] bigint NULL, 
	[YAUGRU] varchar(8000) NULL, 
	[TVAUT_KEY] bigint NULL, 
	[PlantKey_SPC] bigint NULL, 
	[Net value] decimal(38,6) NULL, 
	[SegmentKey] bigint NULL, 
	[BusinessAreaKey] bigint NULL, 
	[Profit_CenterID] bigint NULL, 
	[CustomerGroupKey] bigint NULL, 
	[Payer name] bigint NULL, 
	[CustomerTypeKey] bigint NULL, 
	[BrandKey] bigint NULL, 
	[REASON FOR REJECTION _LINE_] varchar(8000) NULL, 
	[Order reason] varchar(8000) NULL, 
	[Order reason_1] varchar(8000) NULL, 
	[PO Number] varchar(8000) NULL, 
	[Shipment Number] bigint NULL, 
	[Shipping type] varchar(8000) NULL, 
	[SO Created Date] date NULL, 
	[Delivery Creation Date] date NULL, 
	[Confirmation Date] date NULL, 
	[Combined Date] date NULL, 
	[SO_BillingDateKey] varchar(8000) NULL, 
	[Ship-To Party Region] varchar(8000) NULL, 
	[PlanningEnd] varchar(8000) NULL, 
	[PlannedDateCheckin] varchar(8000) NULL, 
	[PlannedTimeCheckIn] varchar(8000) NULL, 
	[Trailer No_] varchar(8000) NULL, 
	[PlannedShipmentEnd] varchar(8000) NULL, 
	[FSL_LoadDelayReason] varchar(8000) NULL, 
	[LoadDelayReasonKey] bigint NULL, 
	[DelayReason] varchar(8000) NULL, 
	[Act. Gds Mvmnt Date] varchar(8000) NULL, 
	[ActGdsMvmntDateKey] bigint NULL, 
	[invoice] varchar(8000) NULL, 
	[Invoice Billing Date] date NULL, 
	[InvoiceBillingDateKey] bigint NULL, 
	[MeasureKey] bigint NULL, 
	[OnTimeDateMeasure] varchar(8000) NULL, 
	[Min_Days] bigint NULL, 
	[Max_Days] bigint NULL, 
	[ValidLine] varchar(8000) NULL, 
	[OnTimeDate] varchar(8000) NULL, 
	[OnTimeDateKey] bigint NULL, 
	[Variance] bigint NULL, 
	[LineOnTimeStatus] varchar(8000) NULL, 
	[LineInFullStatus] varchar(8000) NULL, 
	[TotalLines] bigint NULL, 
	[OnTimeLines] bigint NULL, 
	[InFullLines] bigint NULL, 
	[Order OTIF] bigint NULL, 
	[LineFailureReason] varchar(8000) NULL, 
	[CarrierID] varchar(8000) NULL, 
	[CarrierName] varchar(8000) NULL, 
	[CarrierService] varchar(8000) NULL, 
	[CarrierSCAC_Code] varchar(8000) NULL, 
	[ship_to_zip] varchar(8000) NULL, 
	[SparePartInd] bigint NULL, 
	[YS10N Source] varchar(8000) NULL, 
	[Reason for rejection] varchar(8000) NULL, 
	[SKUPayer] varchar(8000) NULL, 
	[Status] varchar(8000) NULL, 
	[Company Code] varchar(8000) NULL, 
	[ECommerce] varchar(8000) NULL, 
	[ECOM $] float NULL, 
	[Defective Allowance.1] float NULL, 
	[Ship Date] date NULL, 
	[MRP Area] varchar(8000) NULL, 
	[MRPSKU Key] varchar(8000) NULL, 
	[Data Source] varchar(8000) NULL, 
	[SOW] date NULL, 
	[Today] date NULL, 
	[Today SOW] date NULL, 
	[ShipToZip_Clean] varchar(8000) NULL, 
	[Act. Gds Mvmnt Date Converted] date NULL, 
	[Dim Currency Rate.Conversion] float NULL, 
	[Net Value USD] float NULL, 
	[Gross Sales USD] decimal(38,6) NULL, 
	[New Net Value] float NULL, 
	[Parcel $] float NULL, 
	[TL $] float NULL, 
	[LTL $] float NULL, 
	[DTC YRSHP.Storage Location] varchar(8000) NULL, 
	[New Storage Location] varchar(8000) NULL
);