table Dwell
	lineageTag: 893181c6-27d3-40de-a3e3-d7675ce9f0fa

	column Container
		dataType: string
		lineageTag: 8e2d83a6-b19a-4f17-99ff-a267215b5590
		summarizeBy: none
		sourceColumn: Container

		annotation SummarizationSetBy = Automatic

	column 'Cont. Int. Num.'
		dataType: int64
		formatString: 0
		lineageTag: f6528fb7-08e7-48da-b307-bb4ea4e56d84
		summarizeBy: sum
		sourceColumn: Cont. Int. Num.

		annotation SummarizationSetBy = Automatic

	column 'Storage Loc.'
		dataType: string
		lineageTag: a69d85e2-e81c-44c5-a2c7-e062eb34a079
		summarizeBy: none
		sourceColumn: Storage Loc.

		annotation SummarizationSetBy = Automatic

	column 'Transfer Pending TO'
		dataType: int64
		formatString: 0
		lineageTag: 4ba70349-cca9-4ca7-a192-dd39962e81cc
		summarizeBy: sum
		sourceColumn: Transfer Pending TO

		annotation SummarizationSetBy = Automatic

	column 'Date Of Request'
		dataType: int64
		formatString: 0
		lineageTag: 987ce2be-18f0-4586-a387-f420b807c1cb
		summarizeBy: sum
		sourceColumn: Date Of Request

		annotation SummarizationSetBy = Automatic

	column Material
		dataType: int64
		formatString: 0
		lineageTag: a7d47b03-e354-4eed-94c9-ef7b3f8e8b28
		summarizeBy: sum
		sourceColumn: Material

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: c2824837-ac76-498f-b5b5-2cf1754e4a71
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column 'Expect. Arrival Date'
		dataType: int64
		formatString: 0
		lineageTag: 6a041588-79a4-4f9e-9f7f-b3c8d8ed373c
		summarizeBy: sum
		sourceColumn: Expect. Arrival Date

		annotation SummarizationSetBy = Automatic

	column 'Container With Sever'
		dataType: string
		lineageTag: 1667939f-af78-40b5-94ce-9406d3e10e26
		summarizeBy: none
		sourceColumn: Container With Sever

		annotation SummarizationSetBy = Automatic

	column PO
		dataType: string
		lineageTag: d315c331-5b9f-4392-9d04-ee3f8e2a1825
		summarizeBy: none
		sourceColumn: PO

		annotation SummarizationSetBy = Automatic

	column Vessel
		dataType: string
		lineageTag: 9e934c80-4c34-4204-8faa-b087a6a4bb52
		summarizeBy: none
		sourceColumn: Vessel

		annotation SummarizationSetBy = Automatic

	column Manifest
		dataType: string
		lineageTag: 04d6f525-228c-47de-b01b-4fa8698f837d
		summarizeBy: none
		sourceColumn: Manifest

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: int64
		formatString: 0
		lineageTag: bb955f9c-883f-4983-8a3e-d42ed2dcb355
		summarizeBy: sum
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

	column 'Days in Country'
		dataType: int64
		formatString: 0
		lineageTag: b5824f95-45f4-4307-8867-3a0e407cd7a8
		summarizeBy: sum
		sourceColumn: Days in Country

		annotation SummarizationSetBy = Automatic

	column 'Days In Place'
		dataType: int64
		formatString: 0
		lineageTag: b186783f-9b88-4276-a071-e9bd5d1409e0
		summarizeBy: sum
		sourceColumn: Days In Place

		annotation SummarizationSetBy = Automatic

	column 'Reception Date'
		dataType: int64
		formatString: 0
		lineageTag: 367c16ef-a0ad-47c1-9008-a73731f5c3fa
		summarizeBy: sum
		sourceColumn: Reception Date

		annotation SummarizationSetBy = Automatic

	column 'Inb. Del.'
		dataType: int64
		formatString: 0
		lineageTag: bfbe6c42-c767-4389-9199-ec48c6a3b0db
		summarizeBy: sum
		sourceColumn: Inb. Del.

		annotation SummarizationSetBy = Automatic

	column 'Expected PGR'
		dataType: int64
		formatString: 0
		lineageTag: 3d7ae52b-aa4d-400c-84a4-d4e37d87d107
		summarizeBy: sum
		sourceColumn: Expected PGR

		annotation SummarizationSetBy = Automatic

	column User
		dataType: string
		lineageTag: 22ec93c9-4f70-49c5-b57f-c46867fbcc3c
		summarizeBy: none
		sourceColumn: User

		annotation SummarizationSetBy = Automatic

	column 'Mat. Descr.'
		dataType: string
		lineageTag: 91422693-be8d-4a55-a02f-06db6bbc6170
		summarizeBy: none
		sourceColumn: Mat. Descr.

		annotation SummarizationSetBy = Automatic

	column 'Outb.Deliv.'
		dataType: int64
		formatString: 0
		lineageTag: 15bc5e87-bd8b-4032-94bb-01cfdb1d5c38
		summarizeBy: sum
		sourceColumn: Outb.Deliv.

		annotation SummarizationSetBy = Automatic

	column Customer
		dataType: int64
		formatString: 0
		lineageTag: 151a7470-eaeb-470e-ba5e-46d8ba100e95
		summarizeBy: sum
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column Customer_1
		dataType: string
		lineageTag: 5c9c9482-d9c4-437f-8e5c-faac03ab2c5f
		summarizeBy: none
		sourceColumn: Customer_1

		annotation SummarizationSetBy = Automatic

	column 'Stock In QA Inspect.'
		dataType: string
		lineageTag: 3dc3205b-68b5-43ea-88c3-cd557b486fc3
		summarizeBy: none
		sourceColumn: Stock In QA Inspect.

		annotation SummarizationSetBy = Automatic

	column 'Container Full Name'
		dataType: string
		lineageTag: 9a1f1a12-88f7-48d5-9c9d-f222ba7fb03f
		summarizeBy: none
		sourceColumn: Container Full Name

		annotation SummarizationSetBy = Automatic

	partition Dwell = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://keteronline.sharepoint.com/teams/SavannahRDC/Shared%20Documents/PowerBI%20Projects/DL/Jons%20Folder/Ycontainer.xlsx"), null, true),
				    Dwell_Sheet = Source{[Item="Dwell",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Dwell_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Container", type text}, {"Cont. Int. Num.", Int64.Type}, {"Storage Loc.", type text}, {"Transfer Pending TO", Int64.Type}, {"Date Of Request", Int64.Type}, {"Material", Int64.Type}, {"Quantity", Int64.Type}, {"Expect. Arrival Date", Int64.Type}, {"Container With Sever", type text}, {"PO", type text}, {"Vessel", type text}, {"Manifest", type text}, {"Count", Int64.Type}, {"Days in Country", Int64.Type}, {"Days In Place", Int64.Type}, {"Reception Date", Int64.Type}, {"Inb. Del.", Int64.Type}, {"Expected PGR", Int64.Type}, {"User", type text}, {"Mat. Descr.", type text}, {"Outb.Deliv.", Int64.Type}, {"Customer", Int64.Type}, {"Customer_1", type text}, {"Stock In QA Inspect.", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

