table 'THD Filter'
	lineageTag: 561a37ae-49c0-4eca-a2f7-41748858749a

	column 'SKU Level'
		dataType: string
		lineageTag: d131ff36-914f-467f-a1d4-530c1219ecae
		summarizeBy: none
		sourceColumn: SKU Level

		annotation SummarizationSetBy = Automatic

	column 'THD SKU '
		dataType: int64
		formatString: 0
		lineageTag: b98f90ce-1de8-4140-96ea-3deaf8fdf450
		summarizeBy: none
		sourceColumn: "THD SKU "

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: bcca9b30-a867-447e-a12b-4e1266c36755
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column 'Total Forecast '
		dataType: int64
		formatString: 0
		lineageTag: 90fbb07b-75da-4a4e-ac2a-9ddd684324e4
		summarizeBy: none
		sourceColumn: "Total Forecast "

		annotation SummarizationSetBy = Automatic

	column 'Total Invoice'
		dataType: int64
		formatString: 0
		lineageTag: 9b092e23-a1a4-4ea4-a188-89f1fc669dac
		summarizeBy: none
		sourceColumn: Total Invoice

		annotation SummarizationSetBy = Automatic

	column 'AVG Forecast'
		dataType: double
		lineageTag: f4811844-3162-4b83-bc66-985818ee90db
		summarizeBy: none
		sourceColumn: AVG Forecast

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'THD Filter' = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(Web.Contents("https://keteronline-my.sharepoint.com/personal/justinn_keter_com/Documents/Apps/Microsoft Power Query/Uploaded Files/Marshal THD SKUS (Temp for filter on THD Sample).xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "Sheet5", Kind = "Sheet"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Column1", type text}, {"Column4", type text}}),
				  #"Removed columns" = Table.RemoveColumns(#"Changed column type", {"Column1"}),
				  #"Removed top rows" = Table.Skip(#"Removed columns", 1),
				  #"Promoted headers" = Table.PromoteHeaders(#"Removed top rows", [PromoteAllScalars = true]),
				  #"Changed column type 1" = Table.TransformColumnTypes(#"Promoted headers", {{"SKU Level", type text}, {"THD SKU ", Int64.Type}, {"Total Forecast ", Int64.Type}, {"Total Invoice", Int64.Type}, {"AVG Forecast", type number}})
				in
				  #"Changed column type 1"

	annotation PBI_ResultType = Table

