table 'ECOMM FILTER'
	lineageTag: 250a2e27-7c47-45aa-82a5-d515f94366e9

	column Payer
		dataType: int64
		formatString: 0
		lineageTag: f486b7ed-7988-47df-a797-d97f427f1e80
		summarizeBy: none
		sourceColumn: Payer

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 9b11a214-bde8-4286-870b-d2f3413b995f
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column 'ECOMM/ Store'
		dataType: string
		lineageTag: 293964f6-c99d-4dc6-82ae-33b6184928f5
		summarizeBy: none
		sourceColumn: ECOMM/ Store

		annotation SummarizationSetBy = Automatic

	partition 'ECOMM FILTER' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://keteronline.sharepoint.com/teams/KNADemandPlanning/Shared%20Documents/OTIF/Ecomm_Not%20Ecomm%20Master%20File.xlsx"), null, true),
				    Export_Sheet = Source{[Item="Export",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Export_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Payer", Int64.Type}, {"Name", type text}, {"ECOMM/ Store", type text}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"Payer"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Duplicates", each [Payer] <> null and [Payer] <> "")
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

