table 'Profit Centers'
	lineageTag: d4718622-ae41-4206-b356-d52d3325c5fe

	column 'Profit Center'
		dataType: int64
		formatString: 0
		lineageTag: b00afe35-15d2-4b7d-8f11-61904de154ba
		summarizeBy: none
		sourceColumn: Profit Center

		annotation SummarizationSetBy = Automatic

	column 'Profit Center Name'
		dataType: string
		lineageTag: 760fbd67-775e-4ec7-86e5-54503536ccdb
		summarizeBy: none
		sourceColumn: Profit Center Name

		annotation SummarizationSetBy = Automatic

	column BU
		dataType: string
		lineageTag: b33eb5a5-6051-4234-ae34-e40696c141b2
		summarizeBy: none
		sourceColumn: BU

		annotation SummarizationSetBy = Automatic

	partition 'Profit Centers' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://keteronline.sharepoint.com/teams/KNADemandPlanning/Shared%20Documents/OTIF/OTIF%20Calculation%20Template.xlsx"), null, true),
				    #"Profit Centers_Sheet" = Source{[Item="Profit Centers",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Profit Centers_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Profit Center", Int64.Type}, {"Profit Center Name", type text}, {"BU", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

